// This file is automatically generated by qtc from "anyForm.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line views/templates/forms/anyForm.qtpl:1
package forms

//line views/templates/forms/anyForm.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/templates/forms/anyForm.qtpl:1
import (
	"fmt"
	"github.com/ruslanBik4/httpgo/models/db"
	"log"
	"regexp"
	"strconv"
	"strings"
)

//line views/templates/forms/anyForm.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/templates/forms/anyForm.qtpl:10
type FieldStructure struct {
	COLUMN_NAME              string
	DATA_TYPE                string
	COLUMN_DEFAULT           string
	IS_NULLABLE              string
	CHARACTER_SET_NAME       string
	COLUMN_COMMENT           string
	COLUMN_TYPE              string
	CHARACTER_MAXIMUM_LENGTH int
	Value                    string
	IsHidden                 bool
	CSSClass                 string
	TableName                string
	Events                   map[string]string
}
type FieldsTable struct {
	Name     string
	IsDadata bool
	Rows     []FieldStructure
	Hiddens  map[string]string
}

//line views/templates/forms/anyForm.qtpl:32
func (field *FieldStructure) StreamRenderMultiSelect(qw422016 *qt422016.Writer, nameTable, tablePrefix, key, val, titleLabel, required string) {
	//line views/templates/forms/anyForm.qtpl:32
	qw422016.N().S(`
    <label class="control-label" for="`)
	//line views/templates/forms/anyForm.qtpl:33
	qw422016.E().S(tablePrefix + key)
	//line views/templates/forms/anyForm.qtpl:33
	qw422016.N().S(`">`)
	//line views/templates/forms/anyForm.qtpl:33
	qw422016.E().S(titleLabel)
	//line views/templates/forms/anyForm.qtpl:33
	qw422016.N().S(`</label>
    <select id="`)
	//line views/templates/forms/anyForm.qtpl:34
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:34
	qw422016.N().S(`" name="`)
	//line views/templates/forms/anyForm.qtpl:34
	qw422016.E().S(tablePrefix + key)
	//line views/templates/forms/anyForm.qtpl:34
	qw422016.N().S(`" class="controls" multiple `)
	//line views/templates/forms/anyForm.qtpl:34
	qw422016.E().S(required)
	//line views/templates/forms/anyForm.qtpl:34
	qw422016.N().S(` `)
	//line views/templates/forms/anyForm.qtpl:34
	qw422016.E().S(val)
	//line views/templates/forms/anyForm.qtpl:34
	qw422016.N().S(`>
        <option disabled >Выберите несколько значений в списке</option>
        `)
	//line views/templates/forms/anyForm.qtpl:37
	if nameTable == "" {
		nameTable = field.TableName
	}
	nameTable = strings.TrimLeft(key, "setid_")

	//line views/templates/forms/anyForm.qtpl:42
	qw422016.N().S(`
        `)
	//line views/templates/forms/anyForm.qtpl:43
	streamgetOptions(qw422016, nameTable, field.Value)
	//line views/templates/forms/anyForm.qtpl:43
	qw422016.N().S(`
    </select>
`)
//line views/templates/forms/anyForm.qtpl:45
}

//line views/templates/forms/anyForm.qtpl:45
func (field *FieldStructure) WriteRenderMultiSelect(qq422016 qtio422016.Writer, nameTable, tablePrefix, key, val, titleLabel, required string) {
	//line views/templates/forms/anyForm.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:45
	field.StreamRenderMultiSelect(qw422016, nameTable, tablePrefix, key, val, titleLabel, required)
	//line views/templates/forms/anyForm.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:45
}

//line views/templates/forms/anyForm.qtpl:45
func (field *FieldStructure) RenderMultiSelect(nameTable, tablePrefix, key, val, titleLabel, required string) string {
	//line views/templates/forms/anyForm.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:45
	field.WriteRenderMultiSelect(qb422016, nameTable, tablePrefix, key, val, titleLabel, required)
	//line views/templates/forms/anyForm.qtpl:45
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:45
	return qs422016
//line views/templates/forms/anyForm.qtpl:45
}

//line views/templates/forms/anyForm.qtpl:46
func (field *FieldStructure) StreamRenderSelect(qw422016 *qt422016.Writer, tablePrefix, key, val, titleLabel, required string) {
	//line views/templates/forms/anyForm.qtpl:46
	qw422016.N().S(`
    <label class="control-label" for="`)
	//line views/templates/forms/anyForm.qtpl:47
	qw422016.E().S(tablePrefix + key)
	//line views/templates/forms/anyForm.qtpl:47
	qw422016.N().S(`">`)
	//line views/templates/forms/anyForm.qtpl:47
	qw422016.E().S(titleLabel)
	//line views/templates/forms/anyForm.qtpl:47
	qw422016.N().S(`</label>
    <select id="`)
	//line views/templates/forms/anyForm.qtpl:48
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:48
	qw422016.N().S(`" name="`)
	//line views/templates/forms/anyForm.qtpl:48
	qw422016.E().S(tablePrefix + key)
	//line views/templates/forms/anyForm.qtpl:48
	qw422016.N().S(`" class="controls" `)
	//line views/templates/forms/anyForm.qtpl:48
	qw422016.E().S(required)
	//line views/templates/forms/anyForm.qtpl:48
	qw422016.N().S(` `)
	//line views/templates/forms/anyForm.qtpl:48
	qw422016.E().S(val)
	//line views/templates/forms/anyForm.qtpl:48
	qw422016.N().S(`>
        `)
	//line views/templates/forms/anyForm.qtpl:49
	if field.IS_NULLABLE == "YES" && val == "" {
		//line views/templates/forms/anyForm.qtpl:49
		qw422016.N().S(`
            <option value="" selected>Значение можно не указывать</option>
        `)
		//line views/templates/forms/anyForm.qtpl:51
	} else {
		//line views/templates/forms/anyForm.qtpl:51
		qw422016.N().S(`
            <option disabled >Выберите значение из списка</option>
        `)
		//line views/templates/forms/anyForm.qtpl:53
	}
	//line views/templates/forms/anyForm.qtpl:53
	qw422016.N().S(`
        `)
	//line views/templates/forms/anyForm.qtpl:54
	streamgetOptions(qw422016, key[3:], field.Value)
	//line views/templates/forms/anyForm.qtpl:54
	qw422016.N().S(`
    </select>
`)
//line views/templates/forms/anyForm.qtpl:56
}

//line views/templates/forms/anyForm.qtpl:56
func (field *FieldStructure) WriteRenderSelect(qq422016 qtio422016.Writer, tablePrefix, key, val, titleLabel, required string) {
	//line views/templates/forms/anyForm.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:56
	field.StreamRenderSelect(qw422016, tablePrefix, key, val, titleLabel, required)
	//line views/templates/forms/anyForm.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:56
}

//line views/templates/forms/anyForm.qtpl:56
func (field *FieldStructure) RenderSelect(tablePrefix, key, val, titleLabel, required string) string {
	//line views/templates/forms/anyForm.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:56
	field.WriteRenderSelect(qb422016, tablePrefix, key, val, titleLabel, required)
	//line views/templates/forms/anyForm.qtpl:56
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:56
	return qs422016
//line views/templates/forms/anyForm.qtpl:56
}

//line views/templates/forms/anyForm.qtpl:58
func (field *FieldStructure) streamrenderParentSelect(qw422016 *qt422016.Writer, nameTable, key, val, titleLabel, required string) {
	//line views/templates/forms/anyForm.qtpl:58
	qw422016.N().S(`
    <label for="`)
	//line views/templates/forms/anyForm.qtpl:59
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:59
	qw422016.N().S(`">`)
	//line views/templates/forms/anyForm.qtpl:59
	qw422016.E().S(titleLabel)
	//line views/templates/forms/anyForm.qtpl:59
	qw422016.N().S(`</label>
    <select id="`)
	//line views/templates/forms/anyForm.qtpl:60
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:60
	qw422016.N().S(`" name="`)
	//line views/templates/forms/anyForm.qtpl:60
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:60
	qw422016.N().S(`" class="controls" `)
	//line views/templates/forms/anyForm.qtpl:60
	qw422016.E().S(required)
	//line views/templates/forms/anyForm.qtpl:60
	qw422016.N().S(` `)
	//line views/templates/forms/anyForm.qtpl:60
	qw422016.E().S(val)
	//line views/templates/forms/anyForm.qtpl:60
	qw422016.N().S(`>
        `)
	//line views/templates/forms/anyForm.qtpl:61
	if field.IS_NULLABLE == "YES" && val == "" {
		//line views/templates/forms/anyForm.qtpl:61
		qw422016.N().S(`
            <option value="" selected>Значение можно не указывать</option>
        `)
		//line views/templates/forms/anyForm.qtpl:63
	} else {
		//line views/templates/forms/anyForm.qtpl:63
		qw422016.N().S(`
            <option disabled >Выберите значение из списка</option>
        `)
		//line views/templates/forms/anyForm.qtpl:65
	}
	//line views/templates/forms/anyForm.qtpl:65
	qw422016.N().S(`
        `)
	//line views/templates/forms/anyForm.qtpl:67
	if nameTable == "" {
		nameTable = field.TableName
	}

	//line views/templates/forms/anyForm.qtpl:70
	qw422016.N().S(`
        `)
	//line views/templates/forms/anyForm.qtpl:71
	streamgetOptions(qw422016, nameTable, field.Value)
	//line views/templates/forms/anyForm.qtpl:71
	qw422016.N().S(`
    </select>
`)
//line views/templates/forms/anyForm.qtpl:73
}

//line views/templates/forms/anyForm.qtpl:73
func (field *FieldStructure) writerenderParentSelect(qq422016 qtio422016.Writer, nameTable, key, val, titleLabel, required string) {
	//line views/templates/forms/anyForm.qtpl:73
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:73
	field.streamrenderParentSelect(qw422016, nameTable, key, val, titleLabel, required)
	//line views/templates/forms/anyForm.qtpl:73
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:73
}

//line views/templates/forms/anyForm.qtpl:73
func (field *FieldStructure) renderParentSelect(nameTable, key, val, titleLabel, required string) string {
	//line views/templates/forms/anyForm.qtpl:73
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:73
	field.writerenderParentSelect(qb422016, nameTable, key, val, titleLabel, required)
	//line views/templates/forms/anyForm.qtpl:73
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:73
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:73
	return qs422016
//line views/templates/forms/anyForm.qtpl:73
}

//line views/templates/forms/anyForm.qtpl:74
func streamgetOptions(qw422016 *qt422016.Writer, tableName string, value string) {
	//line views/templates/forms/anyForm.qtpl:74
	qw422016.N().S(`
        `)
	//line views/templates/forms/anyForm.qtpl:76
	name := ""
	var listNs db.FieldsTable

	if err := listNs.GetColumnsProp(tableName); err != nil {
		for _, list := range listNs.Rows {
			switch list.COLUMN_NAME {
			case "name":
				name = "name"
			case "title":
				name = "title"
			case "fullname":
				name = "fullname"
			}
		}
	}

	//line views/templates/forms/anyForm.qtpl:91
	qw422016.N().S(`
        `)
	//line views/templates/forms/anyForm.qtpl:92
	if name > "" {
		//line views/templates/forms/anyForm.qtpl:92
		qw422016.N().S(`
            `)
		//line views/templates/forms/anyForm.qtpl:94
		rows := db.DoQuery("select id, " + name + " from " + tableName)
		defer rows.Close()
		selected := ""
		valueID, _ := strconv.Atoi(value)

		//line views/templates/forms/anyForm.qtpl:98
		qw422016.N().S(`
            `)
		//line views/templates/forms/anyForm.qtpl:99
		for rows.Next() {
			//line views/templates/forms/anyForm.qtpl:99
			qw422016.N().S(`
                `)
			//line views/templates/forms/anyForm.qtpl:101
			var id int
			var title string

			if err := rows.Scan(&id, &title); err != nil {
				log.Println(err)
				continue
			}
			if valueID == id {
				selected = "selected"
			} else {
				selected = ""
			}

			//line views/templates/forms/anyForm.qtpl:113
			qw422016.N().S(`
                <option value='`)
			//line views/templates/forms/anyForm.qtpl:114
			qw422016.N().D(id)
			//line views/templates/forms/anyForm.qtpl:114
			qw422016.N().S(`' `)
			//line views/templates/forms/anyForm.qtpl:114
			qw422016.E().S(selected)
			//line views/templates/forms/anyForm.qtpl:114
			qw422016.N().S(`>`)
			//line views/templates/forms/anyForm.qtpl:114
			qw422016.E().S(title)
			//line views/templates/forms/anyForm.qtpl:114
			qw422016.N().S(`</option>
            `)
			//line views/templates/forms/anyForm.qtpl:115
		}
		//line views/templates/forms/anyForm.qtpl:115
		qw422016.N().S(`
        `)
		//line views/templates/forms/anyForm.qtpl:116
	} else {
		//line views/templates/forms/anyForm.qtpl:116
		qw422016.N().S(`
            <option value="-1" selected>Значения не найдены!</option>
        `)
		//line views/templates/forms/anyForm.qtpl:118
	}
	//line views/templates/forms/anyForm.qtpl:118
	qw422016.N().S(`
`)
//line views/templates/forms/anyForm.qtpl:119
}

//line views/templates/forms/anyForm.qtpl:119
func writegetOptions(qq422016 qtio422016.Writer, tableName string, value string) {
	//line views/templates/forms/anyForm.qtpl:119
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:119
	streamgetOptions(qw422016, tableName, value)
	//line views/templates/forms/anyForm.qtpl:119
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:119
}

//line views/templates/forms/anyForm.qtpl:119
func getOptions(tableName string, value string) string {
	//line views/templates/forms/anyForm.qtpl:119
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:119
	writegetOptions(qb422016, tableName, value)
	//line views/templates/forms/anyForm.qtpl:119
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:119
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:119
	return qs422016
//line views/templates/forms/anyForm.qtpl:119
}

//line views/templates/forms/anyForm.qtpl:121
func cutPartFromTitle(title, pattern, defaultStr string) (titleFull, titlePart string) {

	titleFull = title
	if title == "" {
		return "", ""
	}
	posPattern := strings.Index(titleFull, pattern)
	if posPattern > 0 {
		titlePart = titleFull[posPattern+len(pattern):]
		titleFull = titleFull[:posPattern]
	} else {
		titlePart = defaultStr
	}

	return titleFull, titlePart
}
func (field *FieldStructure) GetColumnTitles() (titleFull, titleLabel, placeholder, pattern, dataJson string) {
	titleFull = field.COLUMN_COMMENT
	if titleFull == "" {
		titleLabel = field.COLUMN_NAME
	} else if strings.Index(titleFull, ".") > 0 {
		titleLabel = titleFull[:strings.Index(titleFull, ".")]
	} else {
		titleLabel = titleFull
	}
	titleFull, pattern = cutPartFromTitle(titleFull, "//", "")
	titleFull, dataJson = cutPartFromTitle(titleFull, "{", "")
	titleFull, placeholder = cutPartFromTitle(titleFull, "#", titleFull)

	return titleFull, titleLabel, placeholder, pattern, dataJson
}

//line views/templates/forms/anyForm.qtpl:153
func (ns *FieldsTable) StreamShowAnyForm(qw422016 *qt422016.Writer, Action, Title string) {
	//line views/templates/forms/anyForm.qtpl:153
	qw422016.N().S(`
<form name="f`)
	//line views/templates/forms/anyForm.qtpl:154
	qw422016.E().S(ns.Name)
	//line views/templates/forms/anyForm.qtpl:154
	qw422016.N().S(`" class="form-horizontal row-fluid" target="content" action="`)
	//line views/templates/forms/anyForm.qtpl:154
	qw422016.E().S(Action)
	//line views/templates/forms/anyForm.qtpl:154
	qw422016.N().S(`" method="post"
      onsubmit="return saveForm(this, afterSaveAnyForm);" >
    <h2 class="form-signin-heading">`)
	//line views/templates/forms/anyForm.qtpl:156
	qw422016.E().S(Title)
	//line views/templates/forms/anyForm.qtpl:156
	qw422016.N().S(`</h2>
    `)
	//line views/templates/forms/anyForm.qtpl:157
	if ns.Name > "" {
		//line views/templates/forms/anyForm.qtpl:157
		qw422016.N().S(`
        <input type="hidden" name="table" value="`)
		//line views/templates/forms/anyForm.qtpl:158
		qw422016.E().S(ns.Name)
		//line views/templates/forms/anyForm.qtpl:158
		qw422016.N().S(`" >
    `)
		//line views/templates/forms/anyForm.qtpl:159
	}
	//line views/templates/forms/anyForm.qtpl:159
	qw422016.N().S(`
    `)
	//line views/templates/forms/anyForm.qtpl:160
	for idx, field := range ns.Rows {
		//line views/templates/forms/anyForm.qtpl:160
		qw422016.N().S(`

        `)
		//line views/templates/forms/anyForm.qtpl:163
		key := field.COLUMN_NAME
		titleFull, titleLabel, placeholder, pattern, dataJson := field.GetColumnTitles()
		val := field.Value
		tablePrefix := ""
		required := ""

		if field.IS_NULLABLE == "NO" {
			required = "required"
		}

		if val > "" {
			val = "value=" + val + ""
		} else if field.COLUMN_DEFAULT > "" {
			val = "value=" + field.COLUMN_DEFAULT + ""
		}
		if dataJson > "" {
			dataJson = fmt.Sprintf("data-names='{% s}'", dataJson)
		}
		if field.TableName > "" {
			tablePrefix = field.TableName + ":"
		}
		events := ""
		for name, funcName := range field.Events {
			events += fmt.Sprintf("%s=\"return %s;\"", name, funcName)
		}

		//line views/templates/forms/anyForm.qtpl:188
		qw422016.N().S(`

        `)
		//line views/templates/forms/anyForm.qtpl:190
		if (val > "") && ((key == "id") || field.IsHidden) {
			//line views/templates/forms/anyForm.qtpl:190
			qw422016.N().S(`
            <input type="hidden" name="`)
			//line views/templates/forms/anyForm.qtpl:191
			qw422016.E().S(key)
			//line views/templates/forms/anyForm.qtpl:191
			qw422016.N().S(`" `)
			//line views/templates/forms/anyForm.qtpl:191
			qw422016.E().S(val)
			//line views/templates/forms/anyForm.qtpl:191
			qw422016.N().S(`>
            `)
			//line views/templates/forms/anyForm.qtpl:192
			continue
			//line views/templates/forms/anyForm.qtpl:193
		} else if key == "id" {
			//line views/templates/forms/anyForm.qtpl:193
			qw422016.N().S(`
            `)
			//line views/templates/forms/anyForm.qtpl:194
			continue
			//line views/templates/forms/anyForm.qtpl:195
		}
		//line views/templates/forms/anyForm.qtpl:195
		qw422016.N().S(`

        <div id="divField`)
		//line views/templates/forms/anyForm.qtpl:197
		qw422016.N().D(idx)
		//line views/templates/forms/anyForm.qtpl:197
		qw422016.N().S(`" class="control-group field-`)
		//line views/templates/forms/anyForm.qtpl:197
		qw422016.E().S(key)
		//line views/templates/forms/anyForm.qtpl:197
		qw422016.N().S(` `)
		//line views/templates/forms/anyForm.qtpl:197
		qw422016.E().S(required)
		//line views/templates/forms/anyForm.qtpl:197
		qw422016.N().S(` `)
		//line views/templates/forms/anyForm.qtpl:197
		qw422016.E().S(field.CSSClass)
		//line views/templates/forms/anyForm.qtpl:197
		qw422016.N().S(`"
                    `)
		//line views/templates/forms/anyForm.qtpl:198
		if field.IsHidden {
			//line views/templates/forms/anyForm.qtpl:198
			qw422016.N().S(`style="display:none"`)
			//line views/templates/forms/anyForm.qtpl:198
		}
		//line views/templates/forms/anyForm.qtpl:198
		qw422016.N().S(`
             data-toggle="tooltip" title="`)
		//line views/templates/forms/anyForm.qtpl:199
		qw422016.N().S(titleFull)
		//line views/templates/forms/anyForm.qtpl:199
		qw422016.N().S(`"
        >
        `)
		//line views/templates/forms/anyForm.qtpl:201
		if key == "parent_id" {
			//line views/templates/forms/anyForm.qtpl:201
			qw422016.N().S(`
            `)
			//line views/templates/forms/anyForm.qtpl:202
			field.streamrenderParentSelect(qw422016, ns.Name, key, val, titleLabel, required)
			//line views/templates/forms/anyForm.qtpl:202
			qw422016.N().S(`
        `)
			//line views/templates/forms/anyForm.qtpl:203
		} else if strings.HasPrefix(key, "id_") {
			//line views/templates/forms/anyForm.qtpl:203
			qw422016.N().S(`
            `)
			//line views/templates/forms/anyForm.qtpl:204
			field.StreamRenderSelect(qw422016, tablePrefix, key, val, titleLabel, required)
			//line views/templates/forms/anyForm.qtpl:204
			qw422016.N().S(`
        `)
			//line views/templates/forms/anyForm.qtpl:205
		} else if strings.HasPrefix(key, "setid_") {
			//line views/templates/forms/anyForm.qtpl:205
			qw422016.N().S(`
            `)
			//line views/templates/forms/anyForm.qtpl:206
			field.StreamRenderMultiSelect(qw422016, ns.Name, tablePrefix, key, val, titleLabel, required)
			//line views/templates/forms/anyForm.qtpl:206
			qw422016.N().S(`
        `)
			//line views/templates/forms/anyForm.qtpl:207
		} else {
			//line views/templates/forms/anyForm.qtpl:207
			qw422016.N().S(`

                `)
			//line views/templates/forms/anyForm.qtpl:209
			switch field.DATA_TYPE {
			//line views/templates/forms/anyForm.qtpl:210
			case "tinyint":
				//line views/templates/forms/anyForm.qtpl:210
				qw422016.N().S(`
                        `)
				//line views/templates/forms/anyForm.qtpl:212
				checked := ""
				if field.Value > "" {
					checked = "checked"
				}

				//line views/templates/forms/anyForm.qtpl:216
				qw422016.N().S(`
                        `)
				//line views/templates/forms/anyForm.qtpl:217
				streamrenderCheckBox(qw422016, tablePrefix+key, titleLabel, 1, checked, events, dataJson)
				//line views/templates/forms/anyForm.qtpl:217
				qw422016.N().S(`
                `)
			//line views/templates/forms/anyForm.qtpl:218
			case "enum":
				//line views/templates/forms/anyForm.qtpl:218
				qw422016.N().S(`
                    <label for="`)
				//line views/templates/forms/anyForm.qtpl:219
				qw422016.E().S(key)
				//line views/templates/forms/anyForm.qtpl:219
				qw422016.N().S(`">`)
				//line views/templates/forms/anyForm.qtpl:219
				qw422016.E().S(titleLabel)
				//line views/templates/forms/anyForm.qtpl:219
				qw422016.N().S(`:</label>
                    `)
				//line views/templates/forms/anyForm.qtpl:220
				field.streamrenderEnum(qw422016, tablePrefix+key, required, events, dataJson)
				//line views/templates/forms/anyForm.qtpl:220
				qw422016.N().S(`
                `)
			//line views/templates/forms/anyForm.qtpl:221
			case "set":
				//line views/templates/forms/anyForm.qtpl:221
				qw422016.N().S(`
                    <label for="`)
				//line views/templates/forms/anyForm.qtpl:222
				qw422016.E().S(key)
				//line views/templates/forms/anyForm.qtpl:222
				qw422016.N().S(`">`)
				//line views/templates/forms/anyForm.qtpl:222
				qw422016.E().S(titleLabel)
				//line views/templates/forms/anyForm.qtpl:222
				qw422016.N().S(`:</label>
                    `)
				//line views/templates/forms/anyForm.qtpl:223
				field.streamrenderSet(qw422016, tablePrefix+key, required, events, dataJson)
				//line views/templates/forms/anyForm.qtpl:223
				qw422016.N().S(`
                `)
			//line views/templates/forms/anyForm.qtpl:224
			default:
				//line views/templates/forms/anyForm.qtpl:224
				qw422016.N().S(`
                    <label class="control-label" for="`)
				//line views/templates/forms/anyForm.qtpl:225
				qw422016.E().S(key)
				//line views/templates/forms/anyForm.qtpl:225
				qw422016.N().S(`">`)
				//line views/templates/forms/anyForm.qtpl:225
				qw422016.E().S(titleLabel)
				//line views/templates/forms/anyForm.qtpl:225
				qw422016.N().S(`</label>
                    <input id="`)
				//line views/templates/forms/anyForm.qtpl:226
				qw422016.E().S(key)
				//line views/templates/forms/anyForm.qtpl:226
				qw422016.N().S(`" name="`)
				//line views/templates/forms/anyForm.qtpl:226
				qw422016.E().S(tablePrefix + key)
				//line views/templates/forms/anyForm.qtpl:226
				qw422016.N().S(`" class="controls" placeholder="`)
				//line views/templates/forms/anyForm.qtpl:226
				qw422016.E().S(placeholder)
				//line views/templates/forms/anyForm.qtpl:226
				qw422016.N().S(`"
                        `)
				//line views/templates/forms/anyForm.qtpl:227
				qw422016.E().S(required)
				//line views/templates/forms/anyForm.qtpl:227
				qw422016.N().S(` `)
				//line views/templates/forms/anyForm.qtpl:227
				qw422016.E().S(val)
				//line views/templates/forms/anyForm.qtpl:227
				qw422016.N().S(` `)
				//line views/templates/forms/anyForm.qtpl:227
				qw422016.N().S(events)
				//line views/templates/forms/anyForm.qtpl:227
				qw422016.N().S(` `)
				//line views/templates/forms/anyForm.qtpl:227
				qw422016.N().S(dataJson)
				//line views/templates/forms/anyForm.qtpl:227
				qw422016.N().S(`

                        `)
				//line views/templates/forms/anyForm.qtpl:229
				if field.DATA_TYPE == "int" || field.DATA_TYPE == "double" {
					//line views/templates/forms/anyForm.qtpl:229
					qw422016.N().S(`
                            type="number"
                               `)
					//line views/templates/forms/anyForm.qtpl:231
					if strings.Contains(field.COLUMN_TYPE, "unsigned") {
						//line views/templates/forms/anyForm.qtpl:231
						qw422016.N().S(`min="0"`)
						//line views/templates/forms/anyForm.qtpl:231
					}
					//line views/templates/forms/anyForm.qtpl:231
					qw422016.N().S(`
                        `)
					//line views/templates/forms/anyForm.qtpl:232
				} else if field.DATA_TYPE == "date" {
					//line views/templates/forms/anyForm.qtpl:232
					qw422016.N().S(`
                            type="date"
                        `)
					//line views/templates/forms/anyForm.qtpl:234
				} else if field.DATA_TYPE == "datetime" {
					//line views/templates/forms/anyForm.qtpl:234
					qw422016.N().S(`
                            type="datetime"
                        `)
					//line views/templates/forms/anyForm.qtpl:236
				} else if strings.Contains(key, "email") {
					//line views/templates/forms/anyForm.qtpl:236
					qw422016.N().S(`
                            type="email"
                        `)
					//line views/templates/forms/anyForm.qtpl:238
				} else {
					//line views/templates/forms/anyForm.qtpl:238
					qw422016.N().S(`
                            type="text"
                               `)
					//line views/templates/forms/anyForm.qtpl:240
					if field.CHARACTER_MAXIMUM_LENGTH > 0 {
						//line views/templates/forms/anyForm.qtpl:240
						qw422016.N().S(`
                                    maxlength="`)
						//line views/templates/forms/anyForm.qtpl:241
						qw422016.N().D(field.CHARACTER_MAXIMUM_LENGTH)
						//line views/templates/forms/anyForm.qtpl:241
						qw422016.N().S(`"
                                    `)
						//line views/templates/forms/anyForm.qtpl:242
						if field.CHARACTER_MAXIMUM_LENGTH == 255 {
							//line views/templates/forms/anyForm.qtpl:242
							qw422016.N().S(`
                                        class="input-xlarge"
                                    `)
							//line views/templates/forms/anyForm.qtpl:244
						}
						//line views/templates/forms/anyForm.qtpl:244
						qw422016.N().S(`
                               `)
						//line views/templates/forms/anyForm.qtpl:245
					}
					//line views/templates/forms/anyForm.qtpl:245
					qw422016.N().S(`
                               `)
					//line views/templates/forms/anyForm.qtpl:246
					if pattern > "" {
						//line views/templates/forms/anyForm.qtpl:246
						qw422016.N().S(`pattern="`)
						//line views/templates/forms/anyForm.qtpl:246
						qw422016.N().S(pattern)
						//line views/templates/forms/anyForm.qtpl:246
						qw422016.N().S(`" onkeyup="return validatePattern(this);"`)
						//line views/templates/forms/anyForm.qtpl:246
					}
					//line views/templates/forms/anyForm.qtpl:246
					qw422016.N().S(`
                        `)
					//line views/templates/forms/anyForm.qtpl:247
				}
				//line views/templates/forms/anyForm.qtpl:247
				qw422016.N().S(`
                    />
                `)
				//line views/templates/forms/anyForm.qtpl:249
			}
			//line views/templates/forms/anyForm.qtpl:249
			qw422016.N().S(`

        `)
			//line views/templates/forms/anyForm.qtpl:251
		}
		//line views/templates/forms/anyForm.qtpl:251
		qw422016.N().S(`
        </div>
    `)
		//line views/templates/forms/anyForm.qtpl:253
	}
	//line views/templates/forms/anyForm.qtpl:253
	qw422016.N().S(`
    <div class="form-actions">
        <button class="btn btn-large btn-primary" type="submit">Сохранить</button>

    </div>
</form>
`)
//line views/templates/forms/anyForm.qtpl:259
}

//line views/templates/forms/anyForm.qtpl:259
func (ns *FieldsTable) WriteShowAnyForm(qq422016 qtio422016.Writer, Action, Title string) {
	//line views/templates/forms/anyForm.qtpl:259
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:259
	ns.StreamShowAnyForm(qw422016, Action, Title)
	//line views/templates/forms/anyForm.qtpl:259
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:259
}

//line views/templates/forms/anyForm.qtpl:259
func (ns *FieldsTable) ShowAnyForm(Action, Title string) string {
	//line views/templates/forms/anyForm.qtpl:259
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:259
	ns.WriteShowAnyForm(qb422016, Action, Title)
	//line views/templates/forms/anyForm.qtpl:259
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:259
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:259
	return qs422016
//line views/templates/forms/anyForm.qtpl:259
}

//line views/templates/forms/anyForm.qtpl:260
func (field *FieldStructure) streamrenderSet(qw422016 *qt422016.Writer, key, required, events, dataJson string) {
	//line views/templates/forms/anyForm.qtpl:260
	qw422016.N().S(`
    `)
	//line views/templates/forms/anyForm.qtpl:262
	enumValidator := regexp.MustCompile(`(?:'([^,]+)',?)`)
	fields := enumValidator.FindAllStringSubmatch(field.COLUMN_TYPE, -1)
	checked := ""

	//line views/templates/forms/anyForm.qtpl:265
	qw422016.N().S(`
    `)
	//line views/templates/forms/anyForm.qtpl:266
	for idx, title := range fields {
		//line views/templates/forms/anyForm.qtpl:266
		qw422016.N().S(`
        `)
		//line views/templates/forms/anyForm.qtpl:268
		enumVal := title[len(title)-1]
		if (field.Value > "") && (strings.Index(field.Value, enumVal) > -1) || (field.Value == "") && (enumVal == field.COLUMN_DEFAULT) {
			checked = "checked"
		} else {
			checked = ""
		}

		//line views/templates/forms/anyForm.qtpl:274
		qw422016.N().S(`
        `)
		//line views/templates/forms/anyForm.qtpl:275
		streamrenderCheckBox(qw422016, key+"[]", enumVal, idx, checked, events, dataJson)
		//line views/templates/forms/anyForm.qtpl:275
		qw422016.N().S(`
    `)
		//line views/templates/forms/anyForm.qtpl:276
	}
	//line views/templates/forms/anyForm.qtpl:276
	qw422016.N().S(`
`)
//line views/templates/forms/anyForm.qtpl:277
}

//line views/templates/forms/anyForm.qtpl:277
func (field *FieldStructure) writerenderSet(qq422016 qtio422016.Writer, key, required, events, dataJson string) {
	//line views/templates/forms/anyForm.qtpl:277
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:277
	field.streamrenderSet(qw422016, key, required, events, dataJson)
	//line views/templates/forms/anyForm.qtpl:277
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:277
}

//line views/templates/forms/anyForm.qtpl:277
func (field *FieldStructure) renderSet(key, required, events, dataJson string) string {
	//line views/templates/forms/anyForm.qtpl:277
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:277
	field.writerenderSet(qb422016, key, required, events, dataJson)
	//line views/templates/forms/anyForm.qtpl:277
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:277
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:277
	return qs422016
//line views/templates/forms/anyForm.qtpl:277
}

//line views/templates/forms/anyForm.qtpl:278
func streamrenderCheckBox(qw422016 *qt422016.Writer, key, title string, idx int, checked, events, dataJson string) {
	//line views/templates/forms/anyForm.qtpl:278
	qw422016.N().S(`
    <label class="checkbox" for="`)
	//line views/templates/forms/anyForm.qtpl:279
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:279
	qw422016.N().D(idx)
	//line views/templates/forms/anyForm.qtpl:279
	qw422016.N().S(`">
        <input type="checkbox" id="`)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.N().D(idx)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.N().S(`" name="`)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.N().S(`" value="`)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.E().S(title)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.N().S(`" `)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.E().S(checked)
	//line views/templates/forms/anyForm.qtpl:280
	qw422016.N().S(`
                `)
	//line views/templates/forms/anyForm.qtpl:281
	qw422016.N().S(events)
	//line views/templates/forms/anyForm.qtpl:281
	qw422016.N().S(` `)
	//line views/templates/forms/anyForm.qtpl:281
	qw422016.N().S(dataJson)
	//line views/templates/forms/anyForm.qtpl:281
	qw422016.N().S(`
        />
        `)
	//line views/templates/forms/anyForm.qtpl:283
	qw422016.E().S(title)
	//line views/templates/forms/anyForm.qtpl:283
	qw422016.N().S(`
    </label>
`)
//line views/templates/forms/anyForm.qtpl:285
}

//line views/templates/forms/anyForm.qtpl:285
func writerenderCheckBox(qq422016 qtio422016.Writer, key, title string, idx int, checked, events, dataJson string) {
	//line views/templates/forms/anyForm.qtpl:285
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:285
	streamrenderCheckBox(qw422016, key, title, idx, checked, events, dataJson)
	//line views/templates/forms/anyForm.qtpl:285
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:285
}

//line views/templates/forms/anyForm.qtpl:285
func renderCheckBox(key, title string, idx int, checked, events, dataJson string) string {
	//line views/templates/forms/anyForm.qtpl:285
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:285
	writerenderCheckBox(qb422016, key, title, idx, checked, events, dataJson)
	//line views/templates/forms/anyForm.qtpl:285
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:285
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:285
	return qs422016
//line views/templates/forms/anyForm.qtpl:285
}

//line views/templates/forms/anyForm.qtpl:286
func (field *FieldStructure) streamrenderEnum(qw422016 *qt422016.Writer, key, required, events, dataJson string) {
	//line views/templates/forms/anyForm.qtpl:286
	qw422016.N().S(`
    `)
	//line views/templates/forms/anyForm.qtpl:288
	enumValidator := regexp.MustCompile(`'([^']+)'`)
	fields := enumValidator.FindAllStringSubmatch(field.COLUMN_TYPE, -1)
	renderSelect := len(fields) > 2

	//line views/templates/forms/anyForm.qtpl:291
	qw422016.N().S(`

    `)
	//line views/templates/forms/anyForm.qtpl:293
	if renderSelect {
		//line views/templates/forms/anyForm.qtpl:293
		qw422016.N().S(`
        <select id="`)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.E().S(key)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.N().S(`" name="`)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.E().S(key)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.N().S(`" class="controls" `)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.E().S(required)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.N().S(` `)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.N().S(events)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.N().S(` `)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.N().S(dataJson)
		//line views/templates/forms/anyForm.qtpl:294
		qw422016.N().S(`>
    `)
		//line views/templates/forms/anyForm.qtpl:295
	}
	//line views/templates/forms/anyForm.qtpl:295
	qw422016.N().S(`
    `)
	//line views/templates/forms/anyForm.qtpl:296
	for idx, title := range fields {
		//line views/templates/forms/anyForm.qtpl:296
		qw422016.N().S(`
        `)
		//line views/templates/forms/anyForm.qtpl:298
		enumVal := title[len(title)-1]
		checked, selected := "", ""
		if (field.Value > "") && (field.Value == enumVal) || (field.Value == "") && (enumVal == field.COLUMN_DEFAULT) {
			checked, selected = "checked", "selected"
		}

		//line views/templates/forms/anyForm.qtpl:303
		qw422016.N().S(`
        `)
		//line views/templates/forms/anyForm.qtpl:304
		if renderSelect {
			//line views/templates/forms/anyForm.qtpl:304
			qw422016.N().S(`
            <option value='`)
			//line views/templates/forms/anyForm.qtpl:305
			qw422016.E().S(enumVal)
			//line views/templates/forms/anyForm.qtpl:305
			qw422016.N().S(`' `)
			//line views/templates/forms/anyForm.qtpl:305
			qw422016.E().S(selected)
			//line views/templates/forms/anyForm.qtpl:305
			qw422016.N().S(`>`)
			//line views/templates/forms/anyForm.qtpl:305
			qw422016.E().S(enumVal)
			//line views/templates/forms/anyForm.qtpl:305
			qw422016.N().S(`</option>
        `)
			//line views/templates/forms/anyForm.qtpl:306
		} else {
			//line views/templates/forms/anyForm.qtpl:306
			qw422016.N().S(`
            `)
			//line views/templates/forms/anyForm.qtpl:307
			streamrenderRadioBox(qw422016, key, enumVal, idx, checked, events, dataJson)
			//line views/templates/forms/anyForm.qtpl:307
			qw422016.N().S(`
        `)
			//line views/templates/forms/anyForm.qtpl:308
		}
		//line views/templates/forms/anyForm.qtpl:308
		qw422016.N().S(`
    `)
		//line views/templates/forms/anyForm.qtpl:309
	}
	//line views/templates/forms/anyForm.qtpl:309
	qw422016.N().S(`
    `)
	//line views/templates/forms/anyForm.qtpl:310
	if renderSelect {
		//line views/templates/forms/anyForm.qtpl:310
		qw422016.N().S(`
        </select>
    `)
		//line views/templates/forms/anyForm.qtpl:312
	}
	//line views/templates/forms/anyForm.qtpl:312
	qw422016.N().S(`
`)
//line views/templates/forms/anyForm.qtpl:313
}

//line views/templates/forms/anyForm.qtpl:313
func (field *FieldStructure) writerenderEnum(qq422016 qtio422016.Writer, key, required, events, dataJson string) {
	//line views/templates/forms/anyForm.qtpl:313
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:313
	field.streamrenderEnum(qw422016, key, required, events, dataJson)
	//line views/templates/forms/anyForm.qtpl:313
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:313
}

//line views/templates/forms/anyForm.qtpl:313
func (field *FieldStructure) renderEnum(key, required, events, dataJson string) string {
	//line views/templates/forms/anyForm.qtpl:313
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:313
	field.writerenderEnum(qb422016, key, required, events, dataJson)
	//line views/templates/forms/anyForm.qtpl:313
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:313
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:313
	return qs422016
//line views/templates/forms/anyForm.qtpl:313
}

//line views/templates/forms/anyForm.qtpl:314
func streamrenderRadioBox(qw422016 *qt422016.Writer, key, title string, idx int, checked, events, dataJson string) {
	//line views/templates/forms/anyForm.qtpl:314
	qw422016.N().S(`
    <label class="checkbox" for="`)
	//line views/templates/forms/anyForm.qtpl:315
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:315
	qw422016.N().D(idx)
	//line views/templates/forms/anyForm.qtpl:315
	qw422016.N().S(`">
        <input type="radio" id="`)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.N().D(idx)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.N().S(`" name="`)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.E().S(key)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.N().S(`" value="`)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.E().S(title)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.N().S(`" `)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.E().S(checked)
	//line views/templates/forms/anyForm.qtpl:316
	qw422016.N().S(`
                `)
	//line views/templates/forms/anyForm.qtpl:317
	qw422016.N().S(events)
	//line views/templates/forms/anyForm.qtpl:317
	qw422016.N().S(` `)
	//line views/templates/forms/anyForm.qtpl:317
	qw422016.N().S(dataJson)
	//line views/templates/forms/anyForm.qtpl:317
	qw422016.N().S(`
        />
        `)
	//line views/templates/forms/anyForm.qtpl:319
	qw422016.E().S(title)
	//line views/templates/forms/anyForm.qtpl:319
	qw422016.N().S(`
    </label>
`)
//line views/templates/forms/anyForm.qtpl:321
}

//line views/templates/forms/anyForm.qtpl:321
func writerenderRadioBox(qq422016 qtio422016.Writer, key, title string, idx int, checked, events, dataJson string) {
	//line views/templates/forms/anyForm.qtpl:321
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:321
	streamrenderRadioBox(qw422016, key, title, idx, checked, events, dataJson)
	//line views/templates/forms/anyForm.qtpl:321
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:321
}

//line views/templates/forms/anyForm.qtpl:321
func renderRadioBox(key, title string, idx int, checked, events, dataJson string) string {
	//line views/templates/forms/anyForm.qtpl:321
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:321
	writerenderRadioBox(qb422016, key, title, idx, checked, events, dataJson)
	//line views/templates/forms/anyForm.qtpl:321
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:321
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:321
	return qs422016
//line views/templates/forms/anyForm.qtpl:321
}

//line views/templates/forms/anyForm.qtpl:322
func (fields *FieldsTable) StreamPutDataFrom(qw422016 *qt422016.Writer, ns db.FieldsTable) {
	//line views/templates/forms/anyForm.qtpl:322
	qw422016.N().S(`
`)
	//line views/templates/forms/anyForm.qtpl:324
	for _, field := range ns.Rows {
		fieldStrc := &FieldStructure{
			COLUMN_NAME: field.COLUMN_NAME,
			DATA_TYPE:   field.DATA_TYPE,
			IS_NULLABLE: field.IS_NULLABLE,
			COLUMN_TYPE: field.COLUMN_TYPE,
			Events:      make(map[string]string, 0),
		}
		if field.CHARACTER_SET_NAME.Valid {
			fieldStrc.CHARACTER_SET_NAME = field.CHARACTER_SET_NAME.String
		}
		if field.COLUMN_COMMENT.Valid {
			fieldStrc.COLUMN_COMMENT = field.COLUMN_COMMENT.String
		}
		if field.CHARACTER_MAXIMUM_LENGTH.Valid {
			fieldStrc.CHARACTER_MAXIMUM_LENGTH = int(field.CHARACTER_MAXIMUM_LENGTH.Int64)
		}
		if field.COLUMN_DEFAULT.Valid {
			fieldStrc.COLUMN_DEFAULT = field.COLUMN_DEFAULT.String
		}
		fieldStrc.IsHidden = false
		fields.Rows = append(fields.Rows, *fieldStrc)
	}

	//line views/templates/forms/anyForm.qtpl:347
	qw422016.N().S(`
`)
//line views/templates/forms/anyForm.qtpl:348
}

//line views/templates/forms/anyForm.qtpl:348
func (fields *FieldsTable) WritePutDataFrom(qq422016 qtio422016.Writer, ns db.FieldsTable) {
	//line views/templates/forms/anyForm.qtpl:348
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/forms/anyForm.qtpl:348
	fields.StreamPutDataFrom(qw422016, ns)
	//line views/templates/forms/anyForm.qtpl:348
	qt422016.ReleaseWriter(qw422016)
//line views/templates/forms/anyForm.qtpl:348
}

//line views/templates/forms/anyForm.qtpl:348
func (fields *FieldsTable) PutDataFrom(ns db.FieldsTable) string {
	//line views/templates/forms/anyForm.qtpl:348
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/forms/anyForm.qtpl:348
	fields.WritePutDataFrom(qb422016, ns)
	//line views/templates/forms/anyForm.qtpl:348
	qs422016 := string(qb422016.B)
	//line views/templates/forms/anyForm.qtpl:348
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/forms/anyForm.qtpl:348
	return qs422016
//line views/templates/forms/anyForm.qtpl:348
}
