/*
 * Copyright (c) 2022. Author: Ruslan Bikchentaev. All rights reserved.
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file.
 * Перший приватний програміст.
 */

// Code generated by qtc from "head.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// All the text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//

//line head.qtpl:4
package layouts

//line head.qtpl:4
import (
	"github.com/ruslanBik4/httpgo/views/templates/css"
)

// head for index page.

//line head.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line head.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line head.qtpl:10
type HeadHTMLPage struct {
	Title      string
	Language   string
	Charset    string
	LinkStyles []string
	MetaTags   []string
	Scripts    []string
}

//line head.qtpl:20
func (head *HeadHTMLPage) StreamHeadHTML(qw422016 *qt422016.Writer) {
//line head.qtpl:20
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="`)
//line head.qtpl:22
	qw422016.E().S(head.Language)
//line head.qtpl:22
	qw422016.N().S(`">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="`)
//line head.qtpl:25
	qw422016.E().S(head.Charset)
//line head.qtpl:25
	qw422016.N().S(`">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="httpgo">
    `)
//line head.qtpl:29
	for i := 0; i < len(head.MetaTags); i++ {
//line head.qtpl:29
		qw422016.N().S(`
        `)
//line head.qtpl:30
		qw422016.N().S(head.MetaTags[i])
//line head.qtpl:30
		qw422016.N().S(`
    `)
//line head.qtpl:31
	}
//line head.qtpl:31
	qw422016.N().S(`
    <title>`)
//line head.qtpl:32
	qw422016.E().S(head.Title)
//line head.qtpl:32
	qw422016.N().S(`</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.css" type="text/css" media="screen">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0/css/bootstrap.min.css" integrity="sha512-XWTTruHZEYJsxV3W/lSXG1n3Q39YIWOstqvmFsdNEEQfHoZ6vm6E9GK2OrF6DSJSpIbRbi+Nn0WDPID9O7xB2Q==" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0/css/bootstrap-utilities.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap-responsive.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jScrollPane/2.0.23/style/jquery.jscrollpane.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.formstyler/1.7.8/jquery.formstyler.css">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">

    <!-- Fav and touch icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/build/jquery.datetimepicker.min.css" type="text/css" media="screen">
    `)
//line head.qtpl:53
	for i := 0; i < len(head.LinkStyles); i++ {
//line head.qtpl:53
		qw422016.N().S(`
        `)
//line head.qtpl:54
		qw422016.N().S(head.LinkStyles[i])
//line head.qtpl:54
		qw422016.N().S(`
    `)
//line head.qtpl:55
	}
//line head.qtpl:55
	qw422016.N().S(`
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>
    <!-- forms rendering & validation -->
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js" async></script>
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.js" async></script>
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js" async></script>
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.js" ></script>
    <script  src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.6.8-fix/jquery.nicescroll.min.js" async></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.0/js/bootstrap.min.js" defer></script>
    <!--[if lt IE 10]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.1/jquery.xdomainrequest.min.js" defer></script>
    <![endif]-->
    <script src="https://cdn.rawgit.com/Mikhus/canvas-gauges/gh-pages/download/latest/all/gauge.min.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/build/jquery.datetimepicker.full.min.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js" defer></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jScrollPane/2.0.23/script/jquery.jscrollpane.min.js" defer></script>
    <script  src="https://cdn.jsdelivr.net/jquery.formstyler/1.7.8/jquery.formstyler.min.js"></script>
    `)
//line head.qtpl:72
	for i := 0; i < len(head.Scripts); i++ {
//line head.qtpl:72
		qw422016.N().S(`
        `)
//line head.qtpl:73
		qw422016.N().S(head.Scripts[i])
//line head.qtpl:73
		qw422016.N().S(`
    `)
//line head.qtpl:74
	}
//line head.qtpl:74
	qw422016.N().S(`
    <link href="https://cdn.jsdelivr.net/jquery.suggestions/16.8/css/suggestions.css" type="text/css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/gh/loadingio/loading.css@v2.0.0/dist/loading.min.css" type="text/css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/jquery.suggestions/16.8/js/jquery.suggestions.min.js" defer></script>
    `)
//line head.qtpl:78
	StreamPutStyles(qw422016)
//line head.qtpl:78
	qw422016.N().S(`

</head>

`)
//line head.qtpl:82
}

//line head.qtpl:82
func (head *HeadHTMLPage) WriteHeadHTML(qq422016 qtio422016.Writer) {
//line head.qtpl:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line head.qtpl:82
	head.StreamHeadHTML(qw422016)
//line head.qtpl:82
	qt422016.ReleaseWriter(qw422016)
//line head.qtpl:82
}

//line head.qtpl:82
func (head *HeadHTMLPage) HeadHTML() string {
//line head.qtpl:82
	qb422016 := qt422016.AcquireByteBuffer()
//line head.qtpl:82
	head.WriteHeadHTML(qb422016)
//line head.qtpl:82
	qs422016 := string(qb422016.B)
//line head.qtpl:82
	qt422016.ReleaseByteBuffer(qb422016)
//line head.qtpl:82
	return qs422016
//line head.qtpl:82
}

//line head.qtpl:87
func StreamAdminHead(qw422016 *qt422016.Writer, title string) {
//line head.qtpl:87
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="httpgo">
    <title>`)
//line head.qtpl:95
	qw422016.E().S(title)
//line head.qtpl:95
	qw422016.N().S(`</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="/jquery.formstyler.css">
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <style>
    `)
//line head.qtpl:102
	css.StreamHttpgoMainCSS(qw422016)
//line head.qtpl:102
	qw422016.N().S(`
    </style>
</head>

`)
//line head.qtpl:106
}

//line head.qtpl:106
func WriteAdminHead(qq422016 qtio422016.Writer, title string) {
//line head.qtpl:106
	qw422016 := qt422016.AcquireWriter(qq422016)
//line head.qtpl:106
	StreamAdminHead(qw422016, title)
//line head.qtpl:106
	qt422016.ReleaseWriter(qw422016)
//line head.qtpl:106
}

//line head.qtpl:106
func AdminHead(title string) string {
//line head.qtpl:106
	qb422016 := qt422016.AcquireByteBuffer()
//line head.qtpl:106
	WriteAdminHead(qb422016, title)
//line head.qtpl:106
	qs422016 := string(qb422016.B)
//line head.qtpl:106
	qt422016.ReleaseByteBuffer(qb422016)
//line head.qtpl:106
	return qs422016
//line head.qtpl:106
}
