// This file is automatically generated by qtc from "object.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line object.qtpl:1
package layouts

//line object.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line object.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line object.qtpl:1
func StreamObjectLayout(qw422016 *qt422016.Writer) {
	//line object.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="css/bootstrap-theme.min.css">
	<link rel="stylesheet" type="text/css" href="css/jquery.formstyler.css">
	<link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="css/main.css">

	<title>theTravel</title>
</head>
<body>
	<header>
		<div class="navbar navbar-default navbar-fixed-top">
			<div class="side_logo_wrapper pull-left"><a href=""><img src="images/header-logo.png"></a></div>
			<div class="dropdown pull-right c-user-top-menu">
				<button data-toggle="dropdown" class="dropdown-toggle text-left">
					<img alt="" src="images/aside_left_1.png">
					<span>Александра Якимчук</span>
					<b class="caret"></b>
				</button>
				<ul class="dropdown-menu">
					<li class="travel-icon-089"><a href="">Общая аналитика</a></li>
					<li class="travel-icon-1104"><a href="" >Вернуться в ЛК 82RU</a></li>
					<li class="travel-icon-954"><a href="">Выйти из ЛК и экстранета</a></li>
				</ul>
			</div>
		</div>
	</header>

	<div class="pull-left aside">
		<div class="pull-left aside_left">
			<ul class="nav nav-tabs">
				<li class="active"><a data-toggle="tab" href="#aside1"><img alt="" src="images/aside_left_1.png"></a></li>
				<li><a data-toggle="tab" href="#aside2"><img alt="" src="images/aside_left_1.png"></a></li>
				<li><a href=""><img alt="" src="images/left-add-button.png"></a></li>
			</ul>
		</div>
		<div class="pull-left aside_right">
			<div class="tab-content aside_tabs_contents">
				<div id="aside1" class="tab-pane fade in active">
					<div class="panel-group" id="accordion_aside_parent_1">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion_aside_parentt_1" href="#parent_collapse1">ЧАО «Президент-отель»<b class="caret"></b></a>
								</h4>
							</div>
							<div id="parent_collapse1" class="panel-collapse collapse in">
								<div class="panel-body no_padding">
									<div class="panel-group" id="accordion_aside_1">
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
													<a data-toggle="collapse" data-parent="#accordion_aside_1" class="collapsed" href="#collapse1"><img src="images/aside_left_1.png">ЧАО «Президент-отель»</a>
												</h4>
											</div>
											<div id="collapse1" class="panel-collapse collapse">
												<div class="panel-body">
													текст
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
													<a data-toggle="collapse" data-parent="#accordion_aside_1" class="collapsed" href="#collapse2"><img src="images/aside_left_1.png">Президент отель «Николаевский»</a>
												</h4>
											</div>
											<div id="collapse2" class="panel-collapse collapse">
												<div class="panel-body">
													текст
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
													<a data-toggle="collapse" data-parent="#accordion_aside_1" class="" href="#collapse3"><img src="images/aside_left_1.png">Президент отель «Госпитальная»</a>
												</h4>
											</div>
											<div id="collapse3" class="panel-collapse collapse in">
												<div class="panel-body">
													<ul class="aside_submenu">
														<li><a href=""><span class="travel-icon-1001"></span>Dashboard</a></li>
														<li><a href=""><span class="travel-icon-1379"></span>Объект</a></li>
														<li><a class="ready" href=""><span class="travel-icon-087"></span>Ценообразование</a></li>
														<li><a href=""><span class="travel-icon-007"></span>Бронирование</a></li>
														<li><a class="moderated" href=""><span class="travel-icon-443"></span>Документы</a></li>
														<li><a href="" class="error"><span class="travel-icon-1364"></span>Аналитика</a></li>
														<li><a href=""><span class="travel-icon-1027"></span>Сотрудники</a></li>
													</ul>
												</div>
											</div>
										</div>
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title">
													<a data-toggle="collapse" data-parent="#accordion_aside_1" class="collapsed" href="#collapse4"><img src="images/aside_left_1.png">Президент отель «Киевский»</a>
												</h4>
											</div>
											<div id="collapse4" class="panel-collapse collapse">
												<div class="panel-body">
													текст
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="aside2" class="tab-pane fade">
					2
				</div>
			</div>
		</div>
	</div>


	<div class="content">
		<div class="container-fluid">
			<div class="row no_margin">
				<div class="col-xs-12 no_padding page_top_bg">
					<div class="col-xs-12 h1_medium">
						Общее описание объекта
						<div class="pull-right"><input type="button" class="btn" value="ОТПРАВИТЬ НА МОДЕРАЦИЮ"></div>
					</div>
					<div class="col-xs-12">
						<ol class="breadcrumb c-breadcrumbs">
							<li class="moderated"><a href="#">
								<div class="pull-left travel-icon-1379 breadcrumbs-img"></div>
								<div class="breadcrumbs-text">
									<span class="breadcrumb-number">Шаг 1</span>
									<span class="breadcrumb-name">Номера</span>
								</div>
							</a></li>
							<li class="ready active">
								<a href="#">
								<div class="pull-left breadcrumb-bed-icon breadcrumbs-img"></div>
								<div class="breadcrumbs-text">
									<span class="breadcrumb-number">Шаг 2</span>
									<span class="breadcrumb-name">Номера номера</span>
								</div>
								</a>
							</li>
						</ol>
					</div>
					<div class="col-xs-12 c-page-tabs-list">
						<ul class="nav nav-tabs page_tabs_list">
							<li class="active"><a class="large_button" data-toggle="tab" href="#panel1">Общее</a></li>
							<li><a class="large_button" data-toggle="tab" href="#panel2">Контакты</a></li>
							<li><a class="large_button" data-toggle="tab" href="#panel3">Условия</a></li>
							<li><a class="large_button" data-toggle="tab" href="#panel4">Удобства и услуги</a></li>
							<li><a class="large_button" data-toggle="tab" href="#panel5">Оформление объекта</a></li>
						</ul>
					</div>
				</div>
				<div class="col-xs-12 content-block-wrapper no_padding">
					<div class="tab-content page_tabs_contents">
						<div id="panel1" class="tab-pane fade in active clearfix">
							<div class="col-xs-6 left-padding">
								<div class="col-xs-12 form_elements_container">
									<form action="">
										<div class="col-xs-12 top-padding">
											<input type="text" class="c-input" placeholder="Название объекта, видимое клиентам">
										</div>
										<div class="clearfix">
											<div class="col-xs-6">
												<div class="c-add_logo">
													<input class="c-file_input" type="file">
													<span>Добавить <br/> логотип</span>
												</div>
											</div>
											<div class="col-xs-6">
												<select name="" id="" class="c-select">
													<option value="Тип объекта">Тип объекта</option>
													<option value="Отель">Отель</option>
													<option value="value1">value1</option>
													<option value="value2">value2</option>
												</select>
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6">
												<div class="select-wrap">
													<select name="" id="" class="c-select">
														<option value="Тип объекта">Тип объекта</option>
														<option value="Отель">Отель</option>
													</select>
												</div>
											</div>
											<div class="col-xs-6">
												<div class="select-wrap">
													<select name="" id="" class="c-select">
														<option value="Тип объекта">Тип объекта</option>
														<option value="Отель">Отель</option>
													</select>
												</div>
											</div>
										</div>
										<div class="col-xs-12 clearfix">
											<input type="text" class="c-input" placeholder="Общее количество номеров">
										</div>
										<div class="col-xs-12 clearfix">
											<input type="text" class="c-input" placeholder="Сеть объектов">
										</div>
										<div class="col-xs-12 clearfix">
											<p><label class="c-label" for="textarea">Общее описание объекта</label></p>
											<textarea class="c-textarea" name="" id="textarea" placeholder="Введите общее описание"></textarea>
										</div>
									</div>
								</div>
								<div class="col-xs-6 right-padding">
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12">
											<h5 class="c-h5">Используемый Channel Manager</h5>
											<select name="" id="" class="c-select">
												<option value="Выбрать используемый Channel Manager">Выбрать используемый Channel Manager</option>
												<option value="Отель">Отель</option>
											</select>
											<div class="small-button-wrap clearfix">
												<button class="c-small-button pull-right">подключить</button>
											</div>
										</div>
									</div>
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12">
											<h5 class="c-h5">Формат работы</h5>
											<h6 class="c-h6">Хотите работать в режиме заявки ?</h6>
											<div class="radio-group">
												<label class="c-radio-label" for="radio3"><input name="1" value="Нет" id="radio3" class="c-radio" type="radio"><span>Нет</span></label>
												<label class="c-radio-label" for="radio4"><input name="1" value="Да" id="radio4" class="c-radio" type="radio"><span>Да</span></label>
											</div>
											<div class="c-helper">
												<h6 class="c-6h-bold"><span>?</span>Режим заявки</h6>
												<p class="c-paragraph">На сервисе для гостей объекта вместо кнопки "ЗАБРОНИРОВАТЬ" на выбранном номере будет кнопка "УЗНАТЬ ДОСТУПНОСТЬ". Бронь будет отображаться в текущих бронированиях со статусом "ЗАЯВКА"</p>
											</div>
										</div>
									</div>
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12">
											<h5 class="c-h5">Используемая АСУ</h5>
											<select name="" id="ASU" class="c-select">
												<option value="Выбрать используемую АСУ">Выбрать используемую АСУ</option>
												<option value="Отель">Отель</option>
											</select>
										</div>
									</div>
								</div>
								<div class="next-button-wrap clearfix">
									<button class="c-blue-button pull-right">Далее</button>
								</div>
							</div>
							<div id="panel2" class="tab-pane fade clearfix">
								<div class="col-xs-6 left-padding">
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Месторасположение</h5>
										</div>
										<div class="col-xs-12 clearfix">
											<div class="c-search">
												<input type="search" class="c-input" placeholder="Поиск">
												<span class="travel-icon-606"></span>
											</div>
										</div>
										<div class="col-xs-12 clearfix">
											<div class="c-map-place">
												<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d10159.94472775084!2d30.52048555!3d50.459982!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sua!4v1490114356505" width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Страна">
											</div>
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Регион">
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Город">
											</div>
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Улица">
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Дом">
											</div>
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Корпус">
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Почтовый индекс">
											</div>
										</div>
										<div class="col-xs-12 clearfix">
											<div class="textarea-wrap">
												<textarea class="c-textarea" name="" id="textarea" placeholder="Введите общее описание"></textarea>
											</div>
										</div>
										<div class="col-xs-12 clearfix">
											<div class="textarea-wrap def-margin">
												<textarea class="c-textarea" name="" id="textarea" placeholder="Введите общее описание"></textarea>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-6 right-padding">
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Контакты</h5>
										</div>
										<div class="clearfix">
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Телефон для бронирования">
											</div>
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="Мобильный телефон">
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="E-mail контактный">
											</div>
											<div class="col-xs-6">
												<input type="text" name="value" class="c-input" placeholder="E-mail технического отдела">
												<div class="small-button-wrap clearfix">
													<button class="c-small-button pull-right">Добавить средства связи</button>
												</div>
											</div>
										</div>
										<div class="col-xs-12 clearfix">
											<div class="textarea-wrap with-topline">
												<textarea class="c-textarea" name="" id="textarea" placeholder="Комментарий по формату коммуникации с объектом (удобное время, предпочтительные каналы в определенных случаях)"></textarea>
											</div>
										</div>
									</div>
									<div class="col-xs-12 form_elements_container social">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Онлайн связь</h5>
										</div>
										<div class="col-xs-12 clearfix">
											<input type="text" name="value" class="c-input" placeholder="Сайт">
										</div>
										<div class="clearfix">
											<div class="col-xs-6 clearfix">
												<div class="img-social pull-left">
													<img src="images/fb.png" alt="facebook" >
												</div>
												<div class="input-social pull-left">
													<input type="text" name="value" class="c-input" placeholder="facebook.com/">
												</div>
											</div>
											<div class="col-xs-6 clearfix">
												<div class="img-social pull-left">
													<img src="images/insta.png" alt="instagram" >
												</div>
												<div class="input-social pull-left">
													<input type="text" name="value" class="c-input" placeholder="facebook.com/">
												</div>
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6 clearfix">
												<div class="img-social pull-left">
													<img src="images/vk.png" alt="vkontakte" >
												</div>
												<div class="input-social pull-left">
													<input type="text" name="value" class="c-input" placeholder="facebook.com/">
												</div>
											</div>
											<div class="col-xs-6 clearfix">
												<div class="img-social pull-left">
													<img src="images/linkedin.png" alt="linkedin" >
												</div>
												<div class="input-social pull-left">
													<input type="text" name="value" class="c-input" placeholder="facebook.com/">
												</div>
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6 clearfix">
												<div class="img-social pull-left">
													<img src="images/fb.png" alt="facebook" >
												</div>
												<div class="input-social pull-left">
													<input type="text" name="value" class="c-input" placeholder="facebook.com/">
												</div>
											</div>
											<div class="col-xs-6 clearfix">
												<div class="img-social pull-left">
													<img src="images/youtube.png" alt="youtube" >
												</div>
												<div class="input-social pull-left">
													<input type="text" name="value" class="c-input" placeholder="facebook.com/">
												</div>
											</div>
										</div>
										<div class="clearfix">
											<div class="col-xs-6 clearfix">
												<div class="img-social pull-left">
													<img src="images/twitter.png" alt="twitter" >
												</div>
												<div class="input-social pull-left">
													<input type="text" name="value" class="c-input" placeholder="facebook.com/">
												</div>
											</div>
											<div class="col-xs-6 clearfix">
												<div class="img-social pull-left">
													<img src="images/fb.png" alt="facebook" >
												</div>
												<div class="input-social pull-left">
													<input type="text" name="value" class="c-input" placeholder="facebook.com/">
												</div>
											</div>
										</div>
									</div>
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Расстояние до моря</h5>
										</div>
										<div class="col-xs-12 clearfix">
											<h6 class="c-h6">Объект размещен у моря ?</h6>
											<div class="radio-group">
												<label class="c-radio-label" for="radio1"><input name="2" value="Нет" id="radio1" class="c-radio" type="radio"><span>Нет</span></label>
												<label class="c-radio-label" for="radio2"><input name="2" value="Да" id="radio2" class="c-radio" type="radio"><span>Да</span></label>
											</div>
										</div>
										<div class="col-xs-12 clearfix">
											<div class="group-input pull-left">
												<input type="text" name="value" class="c-input" placeholder="E-mail технического отдела">
											</div>
											<div class="group-select pull-left">
												<select name="" id="" class="c-select">
													<option value="км">км</option>
													<option value="м">м</option>
												</select>
											</div>
										</div>
									</div>
								</div>
								<div class="next-button-wrap clearfix">
									<button class="c-blue-button pull-right">Далее</button>
								</div>
							</div>
							<div id="panel3" class="tab-pane fade">
								<div class="col-xs-4 left-padding">
									<div class="col-xs-12 form_elements_container clearfix">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Расчетное время</h5>
										</div>
										<div class="col-xs-12">
											<div class="c-prefix-select clearfix">
												<span>C</span>
												<select name="" id="" class="c-select">
													<option value="Время заезда">Время заезда</option>
													<option value="9:00">9:00</option>
													<option value="10:00">10:00</option>
													<option value="11:00">11:00</option>
													<option value="12:00">12:00</option>
													<option value="13:00">13:00</option>
												</select>
											</div>
										</div>
										<div class="col-xs-12">
											<div class="c-checkbox-wrap checkbox-margin-bottom">
												<input class="c-checkbox" type="checkbox" id="checkbox">
												<label class="c-checkbox-label" for="checkbox">
													<span>Разрешить другое время заезда</span>
												</label>
											</div>
										</div>
										<div class="col-xs-12">
											<div class="c-prefix-select clearfix">
												<span>C</span>
												<select name="" id="" class="c-select">
													<option value="Время заезда">Время выезда</option>
													<option value="9:00">9:00</option>
													<option value="10:00">10:00</option>
													<option value="11:00">11:00</option>
													<option value="12:00">12:00</option>
													<option value="13:00">13:00</option>
												</select>
											</div>
										</div>
										<div class="col-xs-12">
											<div class="c-checkbox-wrap">
												<label class="c-checkbox-label" for="checkbox">
													<input class="c-checkbox" type="checkbox" id="checkbox">
													<span>Разрешить другое время заезда</span>
												</label>
											</div>
										</div>
									</div>
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12">
											<h5 class="c-h5">Время работы объекта</h5>
											<div class="select-wrap">
												<select name="" id="" class="c-select">
													<option value="Время заезда">Время выезда</option>
													<option value="9:00">9:00</option>
													<option value="10:00">10:00</option>
													<option value="11:00">11:00</option>
													<option value="12:00">12:00</option>
													<option value="13:00">13:00</option>
												</select>
											</div>
											<div class="select-wrap">
												<select name="" id="" class="c-select">
													<option value="Время заезда">Время выезда</option>
													<option value="9:00">9:00</option>
													<option value="10:00">10:00</option>
													<option value="11:00">11:00</option>
													<option value="12:00">12:00</option>
													<option value="13:00">13:00</option>
												</select>
											</div>
											<span class="title-span">Выходные у отдела бронирования:</span>
											<div class="c-checkbox-wrap">
												<label class="c-checkbox-label" for="checkbox1">
													<input class="c-checkbox" type="checkbox" id="checkbox1">
													<span>Пн</span>
												</label>
												<label class="c-checkbox-label" for="checkbox2">
													<input class="c-checkbox" type="checkbox" id="checkbox2">
													<span>Вт</span>
												</label>
												<label class="c-checkbox-label" for="checkbox3">
													<input class="c-checkbox" type="checkbox" id="checkbox3">
													<span>Ср</span>
												</label>
												<label class="c-checkbox-label" for="checkbox4">
													<input class="c-checkbox" type="checkbox" id="checkbox4">
													<span>Чт</span>
												</label>
												<label class="c-checkbox-label" for="checkbox5">
													<input class="c-checkbox" type="checkbox" id="checkbox5">
													<span>Пт</span>
												</label>
												<label class="c-checkbox-label" for="checkbox6">
													<input class="c-checkbox" type="checkbox" id="checkbox6">
													<span>Сб</span>
												</label>
												<label class="c-checkbox-label" for="checkbox7">
													<input class="c-checkbox" type="checkbox" id="checkbox7">
													<span>Вс</span>
												</label>
											</div>
											<div class="small-button-wrap clearfix">
												<button class="c-small-button pull-right">Добавить период</button>
											</div>
										</div>
									</div>
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12">
											<h5 class="c-h5">Языки обслуживания</h5>
											<div class="select-wrap">
												<select name="" id="" class="c-select">
													<option value="Время заезда">Язык владельца (основ.)</option>
													<option value="9:00">9:00</option>
													<option value="10:00">10:00</option>
													<option value="11:00">11:00</option>
													<option value="12:00">12:00</option>
													<option value="13:00">13:00</option>
												</select>
											</div>
											<div class="select-wrap">
												<select name="" id="" class="c-select">
													<option value="Время заезда">Язык персонала</option>
													<option value="9:00">9:00</option>
													<option value="10:00">10:00</option>
													<option value="11:00">11:00</option>
													<option value="12:00">12:00</option>
													<option value="13:00">13:00</option>
												</select>
											</div>
											<div class="small-button-wrap clearfix">
												<button class="c-small-button pull-right">Добавить язык</button>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-4">
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Дети</h5>
										</div>
										<div class="col-xs-12 clearfix">
											<h6 class="c-h6">Разрешаете размещение детей в объекте?</h6>
											<div class="radio-group">
												<label class="c-radio-label" for="radio11"><input name="5" value="Нет" id="radio11" class="c-radio" type="radio"><span>Нет</span></label>
												<label class="c-radio-label" for="radio21"><input name="5" value="Да" id="radio21" class="c-radio" type="radio"><span>Да</span></label>
											</div>
											<div class="c-terms-group">
												<span class="title-span">Группа <span>1</span></span>
												<div class="c-prefix-select clearfix">
													<span>C</span>
													<input type="text" name="value" class="c-input" placeholder="Введите возраст">
													<select name="" id="" class="c-select">
														<option value="Время заезда">Месяц</option>
														<option value="9:00">Лет</option>
													</select>
												</div>
												<div class="c-prefix-select clearfix">
													<span>До</span>
													<input type="text" name="value" class="c-input" placeholder="Введите возраст">
													<select name="" id="" class="c-select">
														<option value="Время заезда">Месяц</option>
														<option value="9:00">Лет</option>
													</select>
												</div>
												<div class="small-button-wrap clearfix">
													<button class="c-small-button pull-right">Добавить группу</button>
												</div>
											</div>
										</div>
									</div>
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Питание</h5>
										</div>
										<div class="col-xs-12 clearfix">
											<h6 class="c-h6">Предусмотрено ли питание в объекте?</h6>
											<div class="radio-group">
												<label class="c-radio-label" for="radio12"><input name="4" value="Нет" id="radio12" class="c-radio" type="radio"><span>Нет</span></label>
												<label class="c-radio-label" for="radio22"><input name="4" value="Да" id="radio22" class="c-radio" type="radio"><span>Да</span></label>
											</div>
											<div class="c-terms-period">
												<span class="title-span">Период <span>1</span></span>
												<div class="c-prefix-select clearfix">
													<div class="select-wrap-book clearfix">
														<span>C</span>
														<select name="" id="" class="c-select">
															<option value="Время заезда">Месяц</option>
															<option value="9:00">Лет</option>
														</select>
														<select name="" id="" class="c-select">
															<option value="Время заезда">Месяц</option>
															<option value="9:00">Лет</option>
														</select>
													</div>
												</div>
												<div class="c-prefix-select clearfix">
													<span>По</span>
													<select name="" id="" class="c-select">
														<option value="Время заезда">Месяц</option>
														<option value="9:00">Лет</option>
													</select>
													<select name="" id="" class="c-select">
														<option value="Время заезда">Месяц</option>
														<option value="9:00">Лет</option>
													</select>
												</div>
												<div class="small-button-wrap clearfix">
													<button class="c-small-button pull-right">Добавить период</button>
												</div>
											</div>
										</div>
									</div>
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Домашние животные</h5>
										</div>
										<div class="col-xs-12 clearfix">
											<h6 class="c-h6">Разрешаете размещение детей в объекте</h6>
											<div class="radio-group">
												<label class="c-radio-label" for="radio13"><input name="3" value="Нет" id="radio13" class="c-radio" type="radio"><span>Нет</span></label>
												<label class="c-radio-label" for="radio23"><input name="3" value="Да" id="radio23" class="c-radio" type="radio"><span>Да</span></label>
											</div>
										</div>
									</div>

								</div>
								<div class="col-xs-4 right-padding">
									<div class="col-xs-12 form_elements_container">
										<div class="col-xs-12 clearfix">
											<h5 class="c-h5">Бронирование</h5>
										</div>
										<div class="col-xs-12">
											<div class="select-wrap-book">
												<select name="" id="" class="c-select">
													<option value="Время заезда">Месяц</option>
													<option value="9:00">Лет</option>
												</select>
												<div class="c-helper">
													<h6 class="c-6h-bold"><span>?</span>min ВРЕМЯ ДО ЗАЕЗДА</h6>
													<p class="c-paragraph">За какое минимальное время гость может забронировать у вас номер (за сутки до заезда, за трое суток, за неделю и тд.).</p>
												</div>
											</div>
										</div>
										<div class="col-xs-12">
											<div class="select-wrap-book">
												<select name="" id="" class="c-select">
													<option value="Время заезда">Месяц</option>
													<option value="9:00">Лет</option>
												</select>
												<div class="c-helper">
													<h6 class="c-6h-bold"><span>?</span>min ВРЕМЯ ДО ЗАЕЗДА</h6>
													<p class="c-paragraph">За какое минимальное время гость может забронировать у вас номер (за сутки до заезда, за трое суток, за неделю и тд.).</p>
												</div>
											</div>
										</div>
										<div class="col-xs-12 clearfix">
											<h6 class="c-h6">ОГРАНИЧЕНО ДАТОЙ?</h6>
											<div class="radio-group">
												<label class="c-radio-label" for="radio13"><input name="3" value="Нет" id="radio13" class="c-radio" type="radio"><span>Нет</span></label>
												<label class="c-radio-label" for="radio23"><input name="3" value="Да" id="radio23" class="c-radio" type="radio"><span>Да</span></label>
											</div>
										</div>
										<div class="select-wrap-book">
											<div class="clearfix">
												<div class="col-md-4">
													<select name="" id="" class="c-select">
														<option value="Время заезда">Месяц</option>
														<option value="9:00">Лет</option>
													</select>
												</div>
												<div class="col-md-4">
													<select name="" id="" class="c-select">
														<option value="Время заезда">Месяц</option>
														<option value="9:00">Лет</option>
													</select>
												</div>
												<div class="col-md-4">
													<select name="" id="" class="c-select">
														<option value="Время заезда">Месяц</option>
														<option value="9:00">Лет</option>
													</select>
												</div>
											</div>
											<div class="c-helper">
												<h6 class="c-6h-bold"><span>?</span>min ВРЕМЯ ДО ЗАЕЗДА</h6>
												<p class="c-paragraph">За какое минимальное время гость может забронировать у вас номер (за сутки до заезда, за трое суток, за неделю и тд.).</p>
											</div>
										</div>
										<div class="col-xs-12 clearfix">
											<select name="" id="" class="c-select">
												<option value="Время заезда">min срок брони номера</option>
												<option value="9:00">Лет</option>
											</select>
											<span class="margin_10 grey">Доступные способы оплаты при заезде</span>
											<select name="" id="" class="c-select">
												<option value="Время заезда">Только банковская карта</option>
												<option value="9:00">Лет</option>
											</select>
										</div>
										<div class="col-xs-12">
											<div class="c-card-group">
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>VISA</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>MAESTRO</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>DINERS CLUB</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>VISA ELECTRON</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>UNION PAY</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>DISCOVER</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>MASTER CARD</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>JCB</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>НСПУ МИР</span>
													</label>
												</div>
												<div class="checkbox-block">
													<label class="c-checkbox-label" for="checkbox7">
														<input class="c-checkbox" type="checkbox" id="checkbox7">
														<span>AMERICAN EXPRESS</span>
													</label>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="next-button-wrap clearfix">
									<button class="c-blue-button pull-right">Далее</button>
								</div>
							</div>
							<div id="panel4" class="tab-pane fade clearfix">
								<div class="col-xs-4 left-padding">
									<ul class="nav nav-tabs c-services-tabs">
										<li class="active">
											<a class="services-tab-btn" data-toggle="tab" href="#accordion0">
												<span class="services-btn-img ">
													<span class="travel-icon-1014 serv-icon"></span>
												</span>
												<span class="services-text">Питание и напитки</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion1">
												<span class="services-btn-img serv-icon">
													<span class="travel-icon-1124 serv-icon"></span>
												</span>
												<span class="services-text">Wi-Fi</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion2">
												<span class="services-btn-img">
													<span class="travel-icon-034 serv-icon"></span>
												</span>
												<span class="services-text">Услуги на стойке регистрации</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion3">
												<span class="services-btn-img">
													<span class="travel-icon-1124 serv-icon"></span>
												</span>
												<span class="services-text">Парковка</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion4">
												<span class="services-btn-img">
													<span class="travel-icon-022 serv-icon"></span>
												</span>
												<span class="services-text">Трансфер</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion5">
												<span class="services-btn-img">
													<span class="travel-icon-511 serv-icon"></span>
												</span>
												<span class="services-text">Бассейны и оздоровительные услуги</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion6">
												<span class="services-btn-img">
													<span class="travel-icon-028 serv-icon"></span>
												</span>
												<span class="services-text">Услуги уборки и чистки</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion7">
												<span class="services-btn-img">
													<span class="travel-icon-370 serv-icon"></span>
												</span>
												<span class="services-text">Детский отдых</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion8">
												<span class="services-btn-img">
													<span class="travel-icon-1345 serv-icon"></span>
												</span>
												<span class="services-text">Лечение (показания)</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion9">
												<span class="services-btn-img">
													<span class="travel-icon-446 serv-icon"></span>
												</span>
												<span class="services-text">Когресс/Бизнес сервис</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion10">
												<span class="services-btn-img">
													<span class="travel-icon-755 serv-icon"></span>
												</span>
												<span class="services-text">Дополнительные услуги</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion11">
												<span class="services-btn-img">
													<span class="travel-icon-378 serv-icon"></span>
												</span>
												<span class="services-text">Спорт и отдых на территории</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion12">
												<span class="services-btn-img">
													<span class="travel-icon-1064 serv-icon"></span>
												</span>
												<span class="services-text">Оборудование на пляже</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion13">
												<span class="services-btn-img">
													<span class="travel-icon-1065 serv-icon"></span>
												</span>
												<span class="services-text">Зоны общественного пользования</span>
											</a>
										</li>
										<li>
											<a class="services-tab-btn" data-toggle="tab" href="#accordion14">
												<span class="services-btn-img">
													<span class="travel-icon-760 serv-icon"></span>
												</span>
												<span class="services-text">Разное</span>
											</a>
										</li>
									</ul>
								</div>
								<div class="col-xs-8 right-padding clearfix">
									<div class="tab-content">
										<div class="panel-group c-services-accordion tab-pane fade in active" id="accordion0" role="tablist" aria-multiselectable="true">
											<div class="panel panel-default">
												<div class="panel-heading" role="tab" id="headingOne">
													<label class="c-checkbox-label" for="checkbox222" role="button" data-toggle="collapse" data-parent="#accordion0" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
														<input class="c-checkbox" type="checkbox" id="checkbox222">
														<span>Специальное диетическое меню (по запросу)</span>
													</label>
												</div>
												<div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
													<div class="panel-body">
														<span class="title-span">Описание выбранного удобства или услуги</span>
														<textarea name="text" id=""  class="c-textarea" placeholder="Общее описание"></textarea>
														<div class="select-wrap">
															<select name="" id="" class="c-select">
																<option value="Тип объекта">Тип объекта</option>
																<option value="Отель">Отель</option>
															</select>
															<div class="margin_10">
																<label for="" class="c-label">Стоимость услуги</label>
															</div>
															<select name="" id="" class="c-select">
																<option value="Тип объекта">Тип объекта</option>
																<option value="Отель">Отель</option>
															</select>
														</div>
														<div class="c-helper">
															<h6 class="c-6h-bold"><span>?</span>Стоимость услуги - платно</h6>
															<p class="c-paragraph">На сервисе для гостей объекта вместо кнопки "ЗАБРОНИРОВАТЬ" на выбранном номере будет кнопка "УЗНАТЬ ДОСТУПНОСТЬ". Бронь будет отображаться в текущих бронированиях со статусом "ЗАЯВКА"</p>
														</div>
														<div class="margin_10">
															<label for="" class="c-label">Темп начисления</label>
														</div>
														<select name="" id="" class="c-select">
															<option value="Тип объекта">Тип объекта</option>
															<option value="Отель">Отель</option>
														</select>
														<div class="c-helper">
															<h6 class="c-6h-bold"><span>?</span>Стоимость услуги - платно</h6>
															<p class="c-paragraph">На сервисе для гостей объекта вместо кнопки "ЗАБРОНИРОВАТЬ" на выбранном номере будет кнопка "УЗНАТЬ ДОСТУПНОСТЬ". Бронь будет отображаться в текущих бронированиях со статусом "ЗАЯВКА"</p>
														</div>
														<div class="margin-top">
															<input type="text" class="c-input" id="look" placeholder="Вид из окна">
															<input type="text" class="c-input" id="look" placeholder="Вид из окна">
															<input type="text" class="c-input" id="look" placeholder="Вид из окна">
														</div>

													</div>
												</div>
											</div>
											<div class="panel panel-default">
												<div class="panel-heading" role="tab" id="headingth">
													<label class="c-checkbox-label" for="checkbox111" role="button" data-toggle="collapse" data-parent="#accordion0" href="#collapseth" aria-expanded="true" aria-controls="collapseth">
														<input class="c-checkbox" type="checkbox" id="checkbox111">
														<span>Еще таба</span>
													</label>
												</div>
												<div id="collapseth" class="panel-collapse collapse" role="tabpanel2" aria-labelledby="headingth">
													<div class="panel-body">
														Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
													</div>
												</div>
											</div>
										</div>


										<div class="panel-group c-services-accordion tab-pane fade" id="accordion1" role="tablist" aria-multiselectable="true">
											<div class="panel panel-default">
												<div class="panel-heading" role="tab" id="headingTwo">
													<label class="c-checkbox-label" for="checkbox333" role="button" data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
														<input class="c-checkbox" type="checkbox" id="checkbox333">
														<span>Специальное диетическое меню</span>
													</label>
												</div>
												<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
													<div class="panel-body">
														Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
													</div>
												</div>
											</div>
										</div>
									</div>


								</div>
							</div>
							<div id="panel5" class="tab-pane fade clearfix">
								<div class="col-xs-5 left-padding">
									<div class="col-xs-12 form_elements_container">

										<div class="c-group-photo">
											<label for="look" class="c-label">Название группы фото</label>
											<input type="text" class="c-input" id="look" placeholder="Вид из окна">
											<textarea name=""  class="c-textarea" placeholder="Введите краткое описание группы фото"></textarea>
											<div class="small-button-wrap clearfix">
												<button class="c-small-button pull-right">Добавить фото</button>
											</div>
										</div>

									</div>
								</div>
								<div class="col-xs-5">
									<div class="col-xs-12 form_elements_container">
										sdsd
									</div>
								</div>
								<div class="col0xs-2 right-padding">
									s
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<footer id="footer" class="navbar-fixed-bottom row-fluid">
		<div class="container-fluid no_padding">
			<div class="container-fluid pull-left footer_aside">
				<div class="row">
					<a href="" class="col-xs-3 travel-icon-1349"></a>
					<a href="" class="col-xs-3 travel-icon-1117"></a>
					<a href="" class="col-xs-3 travel-icon-1261"></a>
					<a href="" class="col-xs-3 footer-faq-link">FAQ</a>
					<div class="c-footer_manager_info">
						<div class="footer_manager_card">
							<div class="pull-left footer_manager_photo">

							</div>
							<div class="pull-left footer_manager_name">
								Назаренко Анна
								<span>Ваш менеджер</span>
							</div>
							<div class="pull-left footer_manager_infolink">i</div>
							<div class="clearfix"></div>
							<div class="footer-manager-contacts">
								<span class="footer-manager-phone"><span class="travel-icon-1117"></span>+7(499)-703-34-80</span>
								<span class="footer-manager-phone"><span class="travel-icon-1117"></span>8-800-700-82-82</span>
								<span class="footer-manager-mail"><span class="travel-icon-1261"></span><a href="mailto:info@mail.com">info@mail.com</a></span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container-fluid no_padding footer_main">
				<div class="row no_margin">
					<div class="col-xs-6 pull-left footer-first-date">
						<div class="col-xs-12">
							Первое заполнения страницы: <span>hh:mm:ss / dd.mm.yyyy</span>
						</div>
						<div class="col-xs-12">
							Сотрудник: <span>Extranet user full name</span>
						</div>
					</div>
					<div class="col-xs-6 pull-right footer-last-date">
						<div class="col-xs-12 text-right ">
							Последнее редактирование страницы: <span>hh:mm:ss / dd.mm.yyyy</span>
						</div>
						<div class="col-xs-12 text-right ">
							Сотрудник: <span>Extranet user full name</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

		<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/jquery.formstyler.min.js"></script>
		<script src="js/main.js"></script>
	</body>
	</html>
`)
//line object.qtpl:1128
}

//line object.qtpl:1128
func WriteObjectLayout(qq422016 qtio422016.Writer) {
	//line object.qtpl:1128
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line object.qtpl:1128
	StreamObjectLayout(qw422016)
	//line object.qtpl:1128
	qt422016.ReleaseWriter(qw422016)
//line object.qtpl:1128
}

//line object.qtpl:1128
func ObjectLayout() string {
	//line object.qtpl:1128
	qb422016 := qt422016.AcquireByteBuffer()
	//line object.qtpl:1128
	WriteObjectLayout(qb422016)
	//line object.qtpl:1128
	qs422016 := string(qb422016.B)
	//line object.qtpl:1128
	qt422016.ReleaseByteBuffer(qb422016)
	//line object.qtpl:1128
	return qs422016
//line object.qtpl:1128
}
