// Code generated by qtc from "search_panel.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line search_panel.qtpl:1
package layouts

//line search_panel.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line search_panel.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line search_panel.qtpl:2
type SearchPanel struct {
	action      string
	counter     int
	labelButton string
	placeholder string
	suggestions string
	showObject  string
}

func NewSearchPanel(action, suggestions, showObject, labelButton, placeholder string, counter int) *SearchPanel {
	if placeholder == "" {
		placeholder = "Smart search"
	}
	return &SearchPanel{
		action,
		counter,
		labelButton,
		placeholder,
		suggestions,
		showObject,
	}
}

//line search_panel.qtpl:25
func (s *SearchPanel) StreamRender(qw422016 *qt422016.Writer) {
//line search_panel.qtpl:25
	qw422016.N().S(` <form id="fSearch" action="`)
//line search_panel.qtpl:26
	qw422016.E().S(s.action)
//line search_panel.qtpl:26
	qw422016.N().S(`" method="GET" target="#content"
   onsubmit="return saveForm(this, `)
//line search_panel.qtpl:27
	qw422016.E().S(s.showObject)
//line search_panel.qtpl:27
	qw422016.N().S(`, function(error, status) { $('#content').html(error.responseText); } );">
         <input type="hidden" name="html" value=true />
         <input type="hidden" name="counter" value=`)
//line search_panel.qtpl:29
	qw422016.N().D(s.counter)
//line search_panel.qtpl:29
	qw422016.N().S(` />
         <input id="inpS" name="name" type="search" placeholder="`)
//line search_panel.qtpl:30
	qw422016.N().S(s.placeholder)
//line search_panel.qtpl:30
	qw422016.N().S(`" required
         autocapitalize="none" autocorrect="off" autocomplete="off" autofocus=true
`)
//line search_panel.qtpl:32
	if s.suggestions > "" {
//line search_panel.qtpl:32
		qw422016.N().S(`         src="`)
//line search_panel.qtpl:33
		qw422016.E().S(s.suggestions)
//line search_panel.qtpl:33
		qw422016.N().S(`"  data="search-name" onkeyup="return inputSearchKeyUp(this,event,true);"
`)
//line search_panel.qtpl:34
	}
//line search_panel.qtpl:34
	qw422016.N().S(`/>
`)
//line search_panel.qtpl:35
	if s.labelButton > "" {
//line search_panel.qtpl:35
		qw422016.N().S(`         <button type="submit"><i class="fa fa-search">`)
//line search_panel.qtpl:36
		qw422016.N().S(s.labelButton)
//line search_panel.qtpl:36
		qw422016.N().S(`</i></button>
`)
//line search_panel.qtpl:37
	}
//line search_panel.qtpl:37
	qw422016.N().S(`        <output></output>
`)
//line search_panel.qtpl:39
	if s.suggestions > "" {
//line search_panel.qtpl:39
		qw422016.N().S(`         <div class="suggestions-wrapper">
            <span class="suggestions-addon" data-addon-type="spinner"></span>
            <select name="id" size=10 class="suggestions-constraints suggestions-select-hide search-name" data-placeholder="search-name"></select>
            <div class="suggestions-suggestions"></div>
         </div>
`)
//line search_panel.qtpl:45
	}
//line search_panel.qtpl:45
	qw422016.N().S(`        <progress value='0' max='100' hidden > </progress>
    </form>
`)
//line search_panel.qtpl:48
}

//line search_panel.qtpl:48
func (s *SearchPanel) WriteRender(qq422016 qtio422016.Writer) {
//line search_panel.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line search_panel.qtpl:48
	s.StreamRender(qw422016)
//line search_panel.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line search_panel.qtpl:48
}

//line search_panel.qtpl:48
func (s *SearchPanel) Render() string {
//line search_panel.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line search_panel.qtpl:48
	s.WriteRender(qb422016)
//line search_panel.qtpl:48
	qs422016 := string(qb422016.B)
//line search_panel.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line search_panel.qtpl:48
	return qs422016
//line search_panel.qtpl:48
}
