// This file is automatically generated by qtc from "table_view.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line views/templates/tables/table_view.qtpl:1
package tables

//line views/templates/tables/table_view.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

// All the text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.
//
// показ табличных данных.

//line views/templates/tables/table_view.qtpl:5
import (
	"database/sql"
	"fmt"
	"github.com/ruslanBik4/httpgo/views/templates/forms"
	"log"
	"strconv"
	"strings"
)

//line views/templates/tables/table_view.qtpl:14
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/templates/tables/table_view.qtpl:14
func (query *QueryStruct) StreamFineTable(qw422016 *qt422016.Writer) {
	//line views/templates/tables/table_view.qtpl:14
	qw422016.N().S(`
        `)
	//line views/templates/tables/table_view.qtpl:16
	if err := query.beforeRender(); err != nil {
		return
	}

	//line views/templates/tables/table_view.qtpl:19
	qw422016.N().S(`
<link href="/tables.css" rel="stylesheet">
<script src="/tables.js"></script>
    <script  src="/webcomponents.js"></script>
<link rel="import" href="/components/paper-datatable/paper-datatable-card.html">
<link rel="import" href="/components/paper-datatable/paper-datatable.html">
<template is="dom-bind" id="app">
<paper-datatable data="{{data}}" progress="True">
            `)
	//line views/templates/tables/table_view.qtpl:27
	for idx, fieldName := range query.columns {
		//line views/templates/tables/table_view.qtpl:27
		qw422016.N().S(`
                `)
		//line views/templates/tables/table_view.qtpl:29
		fieldStruct := query.fields[idx]
		titleLabel := fieldStruct.COLUMN_COMMENT

		//line views/templates/tables/table_view.qtpl:31
		qw422016.N().S(`
	            <paper-datatable-column header="`)
		//line views/templates/tables/table_view.qtpl:32
		qw422016.E().S(titleLabel)
		//line views/templates/tables/table_view.qtpl:32
		qw422016.N().S(`" property="`)
		//line views/templates/tables/table_view.qtpl:32
		qw422016.E().S(fieldName)
		//line views/templates/tables/table_view.qtpl:32
		qw422016.N().S(`" default="-"
	            type=
	            `)
		//line views/templates/tables/table_view.qtpl:34
		switch fieldStruct.DATA_TYPE {
		//line views/templates/tables/table_view.qtpl:35
		case "varchar":
			//line views/templates/tables/table_view.qtpl:35
			qw422016.N().S(` "String" align="left"
	            `)
		//line views/templates/tables/table_view.qtpl:36
		case "date":
			//line views/templates/tables/table_view.qtpl:36
			qw422016.N().S(` "Date"
	            `)
		//line views/templates/tables/table_view.qtpl:37
		case "set", "enum":
			//line views/templates/tables/table_view.qtpl:37
			qw422016.N().S(` "Array"
	            `)
		//line views/templates/tables/table_view.qtpl:38
		default:
			//line views/templates/tables/table_view.qtpl:38
			qw422016.N().S(`  "Number" align="right"
	            `)
			//line views/templates/tables/table_view.qtpl:39
		}
		//line views/templates/tables/table_view.qtpl:39
		qw422016.N().S(`
	            sortable></paper-datatable-column>
            `)
		//line views/templates/tables/table_view.qtpl:41
	}
	//line views/templates/tables/table_view.qtpl:41
	qw422016.N().S(`
</paper-datatable>
</template>
<script>
        var app = document.querySelector('#app');
        app.data = [
        `)
	//line views/templates/tables/table_view.qtpl:47
	for query.Rows.Next() {
		//line views/templates/tables/table_view.qtpl:47
		qw422016.N().S(`
            `)
		//line views/templates/tables/table_view.qtpl:49
		if err := query.Rows.Scan(query.row...); err != nil {
			log.Println(err)
			continue
		}

		//line views/templates/tables/table_view.qtpl:53
		qw422016.N().S(`
`)
		//line views/templates/tables/table_view.qtpl:55
		qw422016.N().S(`{`)
		//line views/templates/tables/table_view.qtpl:57
		for idx, rawField := range query.row {
			//line views/templates/tables/table_view.qtpl:59
			var fieldStruct *forms.FieldStructure

			switch rawField.(type) {
			case *forms.FieldStructure:
				fieldStruct = rawField.(*forms.FieldStructure)
			default:
				fieldStruct = query.fields[idx]
			}
			key := fieldStruct.COLUMN_NAME
			val := fieldStruct.Value

			//line views/templates/tables/table_view.qtpl:69
			qw422016.E().S(key)
			//line views/templates/tables/table_view.qtpl:69
			qw422016.N().S(`:`)
			//line views/templates/tables/table_view.qtpl:70
			switch fieldStruct.DATA_TYPE {
			//line views/templates/tables/table_view.qtpl:71
			case "varchar":
				//line views/templates/tables/table_view.qtpl:71
				qw422016.N().S(`'`)
				//line views/templates/tables/table_view.qtpl:71
				qw422016.N().S(val)
				//line views/templates/tables/table_view.qtpl:71
				qw422016.N().S(`'`)
			//line views/templates/tables/table_view.qtpl:72
			case "date", "datetime":
				//line views/templates/tables/table_view.qtpl:72
				qw422016.N().S(`'`)
				//line views/templates/tables/table_view.qtpl:72
				qw422016.N().S(val)
				//line views/templates/tables/table_view.qtpl:72
				qw422016.N().S(`'`)
			//line views/templates/tables/table_view.qtpl:73
			case "set", "enum":
				//line views/templates/tables/table_view.qtpl:75
				fields := enumValidator.FindAllStringSubmatch(fieldStruct.COLUMN_TYPE, -1)
				comma := ""

				//line views/templates/tables/table_view.qtpl:77
				qw422016.N().S(`[`)
				//line views/templates/tables/table_view.qtpl:79
				for _, value := range fields {
					//line views/templates/tables/table_view.qtpl:80
					qw422016.E().S(comma)
					//line views/templates/tables/table_view.qtpl:80
					qw422016.N().S(`'`)
					//line views/templates/tables/table_view.qtpl:80
					qw422016.N().S(value[len(value)-1])
					//line views/templates/tables/table_view.qtpl:80
					qw422016.N().S(`'`)
					//line views/templates/tables/table_view.qtpl:81
					comma = ","

					//line views/templates/tables/table_view.qtpl:82
				}
				//line views/templates/tables/table_view.qtpl:82
				qw422016.N().S(`]`)
			//line views/templates/tables/table_view.qtpl:84
			default:
				//line views/templates/tables/table_view.qtpl:84
				qw422016.E().S(val)
				//line views/templates/tables/table_view.qtpl:85
			}
			//line views/templates/tables/table_view.qtpl:85
			qw422016.N().S(`,`)
			//line views/templates/tables/table_view.qtpl:86
		}
		//line views/templates/tables/table_view.qtpl:86
		qw422016.N().S(`},`)
		//line views/templates/tables/table_view.qtpl:88
	}
	//line views/templates/tables/table_view.qtpl:89
	if query.Order > "" {
		//line views/templates/tables/table_view.qtpl:89
		qw422016.N().S(`"sort": {"property": "`)
		//line views/templates/tables/table_view.qtpl:91
		qw422016.N().S(query.Order)
		//line views/templates/tables/table_view.qtpl:91
		qw422016.N().S(`","direction": "asc"},`)
		//line views/templates/tables/table_view.qtpl:94
	}
	//line views/templates/tables/table_view.qtpl:94
	qw422016.N().S(`];`)
	//line views/templates/tables/table_view.qtpl:97
	qw422016.N().S(`
			app.toFixedOne = function(value){
				return value.toFixed(1);
			};
			app.toPercentage = function(value){
				return Math.round(value * 10000)/100 + '%';
			};
		</script>
`)
//line views/templates/tables/table_view.qtpl:105
}

//line views/templates/tables/table_view.qtpl:105
func (query *QueryStruct) WriteFineTable(qq422016 qtio422016.Writer) {
	//line views/templates/tables/table_view.qtpl:105
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/tables/table_view.qtpl:105
	query.StreamFineTable(qw422016)
	//line views/templates/tables/table_view.qtpl:105
	qt422016.ReleaseWriter(qw422016)
//line views/templates/tables/table_view.qtpl:105
}

//line views/templates/tables/table_view.qtpl:105
func (query *QueryStruct) FineTable() string {
	//line views/templates/tables/table_view.qtpl:105
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/tables/table_view.qtpl:105
	query.WriteFineTable(qb422016)
	//line views/templates/tables/table_view.qtpl:105
	qs422016 := string(qb422016.B)
	//line views/templates/tables/table_view.qtpl:105
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/tables/table_view.qtpl:105
	return qs422016
//line views/templates/tables/table_view.qtpl:105
}

//line views/templates/tables/table_view.qtpl:107
func (query *QueryStruct) streamrenderHeadTables(qw422016 *qt422016.Writer) {
	//line views/templates/tables/table_view.qtpl:107
	qw422016.N().S(`
<link href="/tables.css" rel="stylesheet">
<script src="/tables.js"></script>
<div class="table">
<div class='thead' >
    <div class='tr' >
        `)
	//line views/templates/tables/table_view.qtpl:114
	var figure, filterFields string
	if query.Order == "" {
		query.Order = "id"
	}

	//line views/templates/tables/table_view.qtpl:118
	qw422016.N().S(`
            `)
	//line views/templates/tables/table_view.qtpl:119
	for idx, fieldName := range query.columns {
		//line views/templates/tables/table_view.qtpl:119
		qw422016.N().S(`
                `)
		//line views/templates/tables/table_view.qtpl:121
		fieldStruct := query.fields[idx]
		key, titleFull, titleLabel := fieldStruct.COLUMN_NAME, fieldStruct.COLUMN_COMMENT, fieldStruct.COLUMN_COMMENT
		if fieldStruct.InputType == "" {
			fieldStruct.InputType = forms.StyleInput(fieldStruct.DATA_TYPE)
		}
		width, maxLen := forms.GetLengthFromType(fieldStruct.InputType)

		if (fieldStruct.DATA_TYPE == "varchar") && (fieldStruct.CHARACTER_MAXIMUM_LENGTH == 255) {
			width, maxLen = 200, 100
		}
		fieldStruct.CSSStyle = fmt.Sprintf("width:%dpx;", width)
		query.widthTable += width
		filterFields += inputFilterField(key, query.Tables[0].Name, fieldStruct)
		if len(titleFull) > maxLen {

			if pos := strings.LastIndex(titleFull[:maxLen+1], " "); pos > 0 {
				titleLabel = titleFull[:pos] + "..."
			} else {
				titleLabel = titleFull[:maxLen] + "..."
			}
		}

		if titleLabel == "" {
			titleLabel = fieldName
		}

		//line views/templates/tables/table_view.qtpl:146
		qw422016.N().S(`
                `)
		//line views/templates/tables/table_view.qtpl:147
		qw422016.N().S(`
                `)
		//line views/templates/tables/table_view.qtpl:148
		if figure != fieldStruct.Figure {
			//line views/templates/tables/table_view.qtpl:148
			qw422016.N().S(`
                    `)
			//line views/templates/tables/table_view.qtpl:149
			if figure > "" {
				//line views/templates/tables/table_view.qtpl:149
				qw422016.N().S(`
                        </div>
                    `)
				//line views/templates/tables/table_view.qtpl:151
			}
			//line views/templates/tables/table_view.qtpl:151
			qw422016.N().S(`
                    `)
			//line views/templates/tables/table_view.qtpl:153
			figure = fieldStruct.Figure

			//line views/templates/tables/table_view.qtpl:154
			qw422016.N().S(`
                    `)
			//line views/templates/tables/table_view.qtpl:155
			if figure > "" {
				//line views/templates/tables/table_view.qtpl:155
				qw422016.N().S(`
                            <div class='td-outer' style="outline: 1px inset gray;">
                                <div class='th' style="outline: 1px outset gray; padding-top: 1px;"> `)
				//line views/templates/tables/table_view.qtpl:157
				qw422016.E().S(figure)
				//line views/templates/tables/table_view.qtpl:157
				qw422016.N().S(`</div>
                    `)
				//line views/templates/tables/table_view.qtpl:158
			}
			//line views/templates/tables/table_view.qtpl:158
			qw422016.N().S(`
                `)
			//line views/templates/tables/table_view.qtpl:159
		}
		//line views/templates/tables/table_view.qtpl:159
		qw422016.N().S(`
                 <div title="`)
		//line views/templates/tables/table_view.qtpl:160
		qw422016.E().S(fieldName)
		//line views/templates/tables/table_view.qtpl:160
		qw422016.N().S(`" class="td`)
		//line views/templates/tables/table_view.qtpl:160
		if fieldName == query.Order {
			//line views/templates/tables/table_view.qtpl:160
			qw422016.N().S(` td-order`)
			//line views/templates/tables/table_view.qtpl:160
		}
		//line views/templates/tables/table_view.qtpl:160
		qw422016.N().S(`"
                 style="`)
		//line views/templates/tables/table_view.qtpl:161
		qw422016.E().S(fieldStruct.CSSStyle)
		//line views/templates/tables/table_view.qtpl:161
		qw422016.N().S(`">
                   <a href="`)
		//line views/templates/tables/table_view.qtpl:162
		qw422016.E().S(query.Href)
		//line views/templates/tables/table_view.qtpl:162
		qw422016.N().S(`/?order=`)
		//line views/templates/tables/table_view.qtpl:162
		qw422016.E().S(fieldName)
		//line views/templates/tables/table_view.qtpl:162
		qw422016.N().S(`" title="`)
		//line views/templates/tables/table_view.qtpl:162
		qw422016.E().S(titleFull)
		//line views/templates/tables/table_view.qtpl:162
		qw422016.N().S(`">`)
		//line views/templates/tables/table_view.qtpl:162
		qw422016.E().S(titleLabel)
		//line views/templates/tables/table_view.qtpl:162
		qw422016.N().S(`</a>
                </div>
            `)
		//line views/templates/tables/table_view.qtpl:164
	}
	//line views/templates/tables/table_view.qtpl:164
	qw422016.N().S(`
            `)
	//line views/templates/tables/table_view.qtpl:165
	if figure > "" {
		//line views/templates/tables/table_view.qtpl:165
		qw422016.N().S(`
                </div>
            `)
		//line views/templates/tables/table_view.qtpl:167
	}
	//line views/templates/tables/table_view.qtpl:167
	qw422016.N().S(`
    </div>
    <form name='fFilter' id='fFilter' class='form-simple tr thead' role='form' action='`)
	//line views/templates/tables/table_view.qtpl:169
	qw422016.E().S(query.Href)
	//line views/templates/tables/table_view.qtpl:169
	qw422016.N().S(`/?filter' method='post'
    target='content' style='width:auto;$style' onsubmit='return SaveObject( this );' enctype='multipart/form-data'
    oninput='return FormIsModified(event, this);' onabort="alert('fFilter');">
        <output name="State" ></output>
        <input name="`)
	//line views/templates/tables/table_view.qtpl:173
	qw422016.E().S(query.Tables[0].Name)
	//line views/templates/tables/table_view.qtpl:173
	qw422016.N().S(`" hidden />
        `)
	//line views/templates/tables/table_view.qtpl:174
	qw422016.N().S(filterFields)
	//line views/templates/tables/table_view.qtpl:174
	qw422016.N().S(`
    </form>
</div>
`)
//line views/templates/tables/table_view.qtpl:177
}

//line views/templates/tables/table_view.qtpl:177
func (query *QueryStruct) writerenderHeadTables(qq422016 qtio422016.Writer) {
	//line views/templates/tables/table_view.qtpl:177
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/tables/table_view.qtpl:177
	query.streamrenderHeadTables(qw422016)
	//line views/templates/tables/table_view.qtpl:177
	qt422016.ReleaseWriter(qw422016)
//line views/templates/tables/table_view.qtpl:177
}

//line views/templates/tables/table_view.qtpl:177
func (query *QueryStruct) renderHeadTables() string {
	//line views/templates/tables/table_view.qtpl:177
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/tables/table_view.qtpl:177
	query.writerenderHeadTables(qb422016)
	//line views/templates/tables/table_view.qtpl:177
	qs422016 := string(qb422016.B)
	//line views/templates/tables/table_view.qtpl:177
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/tables/table_view.qtpl:177
	return qs422016
//line views/templates/tables/table_view.qtpl:177
}

//line views/templates/tables/table_view.qtpl:178
func (query *QueryStruct) StreamRenderTable(qw422016 *qt422016.Writer) {
	//line views/templates/tables/table_view.qtpl:178
	qw422016.N().S(`
        `)
	//line views/templates/tables/table_view.qtpl:180
	if err := query.beforeRender(); err != nil {
		return
	}

	//line views/templates/tables/table_view.qtpl:183
	qw422016.N().S(`
        `)
	//line views/templates/tables/table_view.qtpl:184
	query.streamrenderHeadTables(qw422016)
	//line views/templates/tables/table_view.qtpl:184
	qw422016.N().S(`
        `)
	//line views/templates/tables/table_view.qtpl:185
	query.streamrenderBodyTables(qw422016)
	//line views/templates/tables/table_view.qtpl:185
	qw422016.N().S(`
`)
//line views/templates/tables/table_view.qtpl:186
}

//line views/templates/tables/table_view.qtpl:186
func (query *QueryStruct) WriteRenderTable(qq422016 qtio422016.Writer) {
	//line views/templates/tables/table_view.qtpl:186
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/tables/table_view.qtpl:186
	query.StreamRenderTable(qw422016)
	//line views/templates/tables/table_view.qtpl:186
	qt422016.ReleaseWriter(qw422016)
//line views/templates/tables/table_view.qtpl:186
}

//line views/templates/tables/table_view.qtpl:186
func (query *QueryStruct) RenderTable() string {
	//line views/templates/tables/table_view.qtpl:186
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/tables/table_view.qtpl:186
	query.WriteRenderTable(qb422016)
	//line views/templates/tables/table_view.qtpl:186
	qs422016 := string(qb422016.B)
	//line views/templates/tables/table_view.qtpl:186
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/tables/table_view.qtpl:186
	return qs422016
//line views/templates/tables/table_view.qtpl:186
}

//line views/templates/tables/table_view.qtpl:187
func StreamShowTable(qw422016 *qt422016.Writer, tableName string, fields forms.FieldsTable, rows *sql.Rows) {
	//line views/templates/tables/table_view.qtpl:187
	qw422016.N().S(`
        `)
	//line views/templates/tables/table_view.qtpl:189
	var query QueryStruct
	query.Rows = rows
	query.Href = "/admin/table/" + tableName
	query.HrefEdit = "/admin/row/edit/?table=" + tableName + "&id="
	query.Tables = append(query.Tables, &fields)

	if err := query.beforeRender(); err != nil {
		return
	}

	//line views/templates/tables/table_view.qtpl:198
	qw422016.N().S(`
        `)
	//line views/templates/tables/table_view.qtpl:199
	query.streamrenderHeadTables(qw422016)
	//line views/templates/tables/table_view.qtpl:199
	qw422016.N().S(`
        `)
	//line views/templates/tables/table_view.qtpl:200
	query.streamrenderBodyTables(qw422016)
	//line views/templates/tables/table_view.qtpl:200
	qw422016.N().S(`
`)
//line views/templates/tables/table_view.qtpl:201
}

//line views/templates/tables/table_view.qtpl:201
func WriteShowTable(qq422016 qtio422016.Writer, tableName string, fields forms.FieldsTable, rows *sql.Rows) {
	//line views/templates/tables/table_view.qtpl:201
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/tables/table_view.qtpl:201
	StreamShowTable(qw422016, tableName, fields, rows)
	//line views/templates/tables/table_view.qtpl:201
	qt422016.ReleaseWriter(qw422016)
//line views/templates/tables/table_view.qtpl:201
}

//line views/templates/tables/table_view.qtpl:201
func ShowTable(tableName string, fields forms.FieldsTable, rows *sql.Rows) string {
	//line views/templates/tables/table_view.qtpl:201
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/tables/table_view.qtpl:201
	WriteShowTable(qb422016, tableName, fields, rows)
	//line views/templates/tables/table_view.qtpl:201
	qs422016 := string(qb422016.B)
	//line views/templates/tables/table_view.qtpl:201
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/tables/table_view.qtpl:201
	return qs422016
//line views/templates/tables/table_view.qtpl:201
}

//line views/templates/tables/table_view.qtpl:202
func (query *QueryStruct) streamrenderBodyTables(qw422016 *qt422016.Writer) {
	//line views/templates/tables/table_view.qtpl:202
	qw422016.N().S(`
<div id="table_body" >
        `)
	//line views/templates/tables/table_view.qtpl:204
	for query.Rows.Next() {
		//line views/templates/tables/table_view.qtpl:204
		qw422016.N().S(`
            `)
		//line views/templates/tables/table_view.qtpl:206
		if err := query.Rows.Scan(query.row...); err != nil {
			log.Println(err)
			continue
		}

		required, tablePrefix, titleLabel := "", "", ""

		//line views/templates/tables/table_view.qtpl:212
		qw422016.N().S(`
        <div class='tr' style='$style_div'>
            `)
		//line views/templates/tables/table_view.qtpl:214
		for idx, rawField := range query.row {
			//line views/templates/tables/table_view.qtpl:214
			qw422016.N().S(`
                `)
			//line views/templates/tables/table_view.qtpl:216
			var fieldStruct *forms.FieldStructure

			switch rawField.(type) {
			case *forms.FieldStructure:
				fieldStruct = rawField.(*forms.FieldStructure)
			default:
				fieldStruct = query.fields[idx]
			}
			key := fieldStruct.COLUMN_NAME
			val := fieldStruct.Value
			fields := fieldStruct.Table
			nameInput := tablePrefix + key
			dataJson := ""
			if dataJson > "" {
				dataJson = fmt.Sprintf(`data-names="{% s}"`, dataJson)
			}
			events := ""
			for name, funcName := range fieldStruct.Events {
				events += fmt.Sprintf(`%s="return %s;"`, name, funcName)
			}

			//line views/templates/tables/table_view.qtpl:236
			qw422016.N().S(`
                <div name="`)
			//line views/templates/tables/table_view.qtpl:237
			qw422016.E().S(key)
			//line views/templates/tables/table_view.qtpl:237
			qw422016.N().S(`" class="td `)
			//line views/templates/tables/table_view.qtpl:237
			qw422016.N().S(required)
			//line views/templates/tables/table_view.qtpl:237
			qw422016.N().S(` field-`)
			//line views/templates/tables/table_view.qtpl:237
			qw422016.E().S(nameInput)
			//line views/templates/tables/table_view.qtpl:237
			qw422016.N().S(` `)
			//line views/templates/tables/table_view.qtpl:237
			qw422016.E().S(fieldStruct.CSSClass)
			//line views/templates/tables/table_view.qtpl:237
			qw422016.N().S(`"
                         style="`)
			//line views/templates/tables/table_view.qtpl:238
			qw422016.E().S(fieldStruct.CSSStyle)
			//line views/templates/tables/table_view.qtpl:238
			qw422016.N().S(`;margin:auto; height:auto;">
                `)
			//line views/templates/tables/table_view.qtpl:239
			if idx == 0 {
				//line views/templates/tables/table_view.qtpl:239
				qw422016.N().S(`
                    <a href="`)
				//line views/templates/tables/table_view.qtpl:240
				qw422016.N().S(query.HrefEdit)
				//line views/templates/tables/table_view.qtpl:240
				qw422016.E().S(val)
				//line views/templates/tables/table_view.qtpl:240
				qw422016.N().S(`" target="content">`)
				//line views/templates/tables/table_view.qtpl:240
				qw422016.E().S(val)
				//line views/templates/tables/table_view.qtpl:240
				qw422016.N().S(`</a>
                    `)
				//line views/templates/tables/table_view.qtpl:242
				tablePrefix = fields.Name
				fields.ID, _ = strconv.Atoi(val)

				//line views/templates/tables/table_view.qtpl:244
				qw422016.N().S(`
                `)
				//line views/templates/tables/table_view.qtpl:245
			} else if fieldStruct.Html > "" {
				//line views/templates/tables/table_view.qtpl:245
				qw422016.N().S(`
                    `)
				//line views/templates/tables/table_view.qtpl:246
				qw422016.N().S(fieldStruct.Html)
				//line views/templates/tables/table_view.qtpl:246
				qw422016.N().S(`
                `)
				//line views/templates/tables/table_view.qtpl:247
			} else {
				//line views/templates/tables/table_view.qtpl:247
				qw422016.N().S(`
                `)
				//line views/templates/tables/table_view.qtpl:250
				qw422016.N().S(`
                        `)
				//line views/templates/tables/table_view.qtpl:251
				if key == "parent_id" {
					//line views/templates/tables/table_view.qtpl:251
					qw422016.N().S(`
                            `)
					//line views/templates/tables/table_view.qtpl:252
					fieldStruct.StreamRenderParentSelect(qw422016, fields.Name, key, val, titleLabel, required, events, dataJson)
					//line views/templates/tables/table_view.qtpl:252
					qw422016.N().S(`
                        `)
					//line views/templates/tables/table_view.qtpl:253
				} else if strings.HasPrefix(key, "id_") {
					//line views/templates/tables/table_view.qtpl:253
					qw422016.N().S(`
                            `)
					//line views/templates/tables/table_view.qtpl:254
					fieldStruct.StreamRenderForeignSelect(qw422016, tablePrefix, key, val, titleLabel, required, events, dataJson)
					//line views/templates/tables/table_view.qtpl:254
					qw422016.N().S(`
                        `)
					//line views/templates/tables/table_view.qtpl:255
				} else if strings.HasPrefix(key, "setid_") || strings.HasPrefix(key, "nodeid_") {
					//line views/templates/tables/table_view.qtpl:255
					qw422016.N().S(`
                            `)
					//line views/templates/tables/table_view.qtpl:256
					fieldStruct.StreamRenderMultiSelect(qw422016, fields, tablePrefix, key, val, "См. ", required)
					//line views/templates/tables/table_view.qtpl:256
					qw422016.N().S(`
                        `)
					//line views/templates/tables/table_view.qtpl:257
				} else if strings.HasPrefix(key, "tableid_") {
					//line views/templates/tables/table_view.qtpl:257
					qw422016.N().S(`
                            `)
					//line views/templates/tables/table_view.qtpl:258
					fieldStruct.StreamRenderTable(qw422016, fields, tablePrefix, key, val, "Табл", required)
					//line views/templates/tables/table_view.qtpl:258
					qw422016.N().S(`
                        `)
					//line views/templates/tables/table_view.qtpl:259
				} else {
					//line views/templates/tables/table_view.qtpl:259
					qw422016.N().S(`
                            `)
					//line views/templates/tables/table_view.qtpl:260
					switch fieldStruct.DATA_TYPE {
					//line views/templates/tables/table_view.qtpl:261
					case "tinyint":
						//line views/templates/tables/table_view.qtpl:261
						qw422016.N().S(`
                                    `)
						//line views/templates/tables/table_view.qtpl:263
						checked := ""
						if val == "1" {
							checked = "checked"
						}

						//line views/templates/tables/table_view.qtpl:267
						qw422016.N().S(`
                                    `)
						//line views/templates/tables/table_view.qtpl:268
						forms.StreamRenderCheckBox(qw422016, nameInput, "1", titleLabel, 1, checked, required, events, dataJson)
						//line views/templates/tables/table_view.qtpl:268
						qw422016.N().S(`
                            `)
					//line views/templates/tables/table_view.qtpl:269
					case "enum":
						//line views/templates/tables/table_view.qtpl:269
						qw422016.N().S(`
                                `)
						//line views/templates/tables/table_view.qtpl:270
						t := fieldStruct.RenderEnum(nameInput, val, required, events, dataJson)

						//line views/templates/tables/table_view.qtpl:270
						qw422016.N().S(`
                                `)
						//line views/templates/tables/table_view.qtpl:271
						qw422016.N().S(t)
						//line views/templates/tables/table_view.qtpl:271
						qw422016.N().S(`
                            `)
					//line views/templates/tables/table_view.qtpl:272
					case "set":
						//line views/templates/tables/table_view.qtpl:272
						qw422016.N().S(`
                                `)
						//line views/templates/tables/table_view.qtpl:273
						t := fieldStruct.RenderSet(nameInput, val, required, events, dataJson)

						//line views/templates/tables/table_view.qtpl:273
						qw422016.N().S(`
                                `)
						//line views/templates/tables/table_view.qtpl:274
						qw422016.N().S(t)
						//line views/templates/tables/table_view.qtpl:274
						qw422016.N().S(`
                            `)
					//line views/templates/tables/table_view.qtpl:275
					case "text":
						//line views/templates/tables/table_view.qtpl:275
						qw422016.N().S(`
                                <p id="`)
						//line views/templates/tables/table_view.qtpl:276
						qw422016.E().S(key)
						//line views/templates/tables/table_view.qtpl:276
						qw422016.N().S(`" name="`)
						//line views/templates/tables/table_view.qtpl:276
						qw422016.E().S(nameInput)
						//line views/templates/tables/table_view.qtpl:276
						qw422016.N().S(`" class="controls"  `)
						//line views/templates/tables/table_view.qtpl:276
						qw422016.N().S(events)
						//line views/templates/tables/table_view.qtpl:276
						qw422016.N().S(` `)
						//line views/templates/tables/table_view.qtpl:276
						qw422016.N().S(dataJson)
						//line views/templates/tables/table_view.qtpl:276
						qw422016.N().S(`>
                                    `)
						//line views/templates/tables/table_view.qtpl:277
						qw422016.N().S(val)
						//line views/templates/tables/table_view.qtpl:277
						qw422016.N().S(`
                                </p>
                            `)
					//line views/templates/tables/table_view.qtpl:279
					case "blob":
						//line views/templates/tables/table_view.qtpl:279
						qw422016.N().S(`
                                <image src="/images/expand_hover.png" />
                            `)
					//line views/templates/tables/table_view.qtpl:281
					default:
						//line views/templates/tables/table_view.qtpl:281
						qw422016.N().S(`
                                `)
						//line views/templates/tables/table_view.qtpl:282
						if fieldStruct.LinkTD > "" {
							//line views/templates/tables/table_view.qtpl:282
							qw422016.N().S(`
                                 <a href="`)
							//line views/templates/tables/table_view.qtpl:283
							qw422016.N().S(fieldStruct.LinkTD)
							//line views/templates/tables/table_view.qtpl:283
							qw422016.N().S(`?id=`)
							//line views/templates/tables/table_view.qtpl:283
							qw422016.N().D(fields.ID)
							//line views/templates/tables/table_view.qtpl:283
							qw422016.N().S(`" target="_blank">`)
							//line views/templates/tables/table_view.qtpl:283
							qw422016.E().S(val)
							//line views/templates/tables/table_view.qtpl:283
							qw422016.N().S(`</a>
                                 `)
							//line views/templates/tables/table_view.qtpl:284
						} else {
							//line views/templates/tables/table_view.qtpl:284
							qw422016.N().S(`
                                    `)
							//line views/templates/tables/table_view.qtpl:285
							qw422016.E().S(val)
							//line views/templates/tables/table_view.qtpl:285
							qw422016.N().S(`
                                 `)
							//line views/templates/tables/table_view.qtpl:286
						}
						//line views/templates/tables/table_view.qtpl:286
						qw422016.N().S(`
                            `)
						//line views/templates/tables/table_view.qtpl:287
					}
					//line views/templates/tables/table_view.qtpl:287
					qw422016.N().S(`
                        `)
					//line views/templates/tables/table_view.qtpl:288
				}
				//line views/templates/tables/table_view.qtpl:288
				qw422016.N().S(`
                `)
				//line views/templates/tables/table_view.qtpl:289
			}
			//line views/templates/tables/table_view.qtpl:289
			qw422016.N().S(`
                </div> <!-- field -->
            `)
			//line views/templates/tables/table_view.qtpl:291
		}
		//line views/templates/tables/table_view.qtpl:291
		qw422016.N().S(`
            `)
		//line views/templates/tables/table_view.qtpl:292
		for _, fieldStruct := range query.PostFields {
			//line views/templates/tables/table_view.qtpl:292
			qw422016.N().S(`
                <div name="`)
			//line views/templates/tables/table_view.qtpl:293
			qw422016.E().S(fieldStruct.COLUMN_NAME)
			//line views/templates/tables/table_view.qtpl:293
			qw422016.N().S(`" class="td `)
			//line views/templates/tables/table_view.qtpl:293
			qw422016.E().S(fieldStruct.CSSClass)
			//line views/templates/tables/table_view.qtpl:293
			qw422016.N().S(`"
                         style="`)
			//line views/templates/tables/table_view.qtpl:294
			qw422016.E().S(fieldStruct.CSSStyle)
			//line views/templates/tables/table_view.qtpl:294
			qw422016.N().S(`;margin:auto; height:auto;" >
                    `)
			//line views/templates/tables/table_view.qtpl:295
			qw422016.N().S(fieldStruct.Html)
			//line views/templates/tables/table_view.qtpl:295
			qw422016.N().S(`
                </div> <!-- field -->
            `)
			//line views/templates/tables/table_view.qtpl:297
		}
		//line views/templates/tables/table_view.qtpl:297
		qw422016.N().S(`
        </div> <!-- tr -->
        `)
		//line views/templates/tables/table_view.qtpl:299
	}
	//line views/templates/tables/table_view.qtpl:299
	qw422016.N().S(`
    </div>
</div>
`)
//line views/templates/tables/table_view.qtpl:302
}

//line views/templates/tables/table_view.qtpl:302
func (query *QueryStruct) writerenderBodyTables(qq422016 qtio422016.Writer) {
	//line views/templates/tables/table_view.qtpl:302
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/tables/table_view.qtpl:302
	query.streamrenderBodyTables(qw422016)
	//line views/templates/tables/table_view.qtpl:302
	qt422016.ReleaseWriter(qw422016)
//line views/templates/tables/table_view.qtpl:302
}

//line views/templates/tables/table_view.qtpl:302
func (query *QueryStruct) renderBodyTables() string {
	//line views/templates/tables/table_view.qtpl:302
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/tables/table_view.qtpl:302
	query.writerenderBodyTables(qb422016)
	//line views/templates/tables/table_view.qtpl:302
	qs422016 := string(qb422016.B)
	//line views/templates/tables/table_view.qtpl:302
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/tables/table_view.qtpl:302
	return qs422016
//line views/templates/tables/table_view.qtpl:302
}

//line views/templates/tables/table_view.qtpl:303
func streamrenderFilterSelect(qw422016 *qt422016.Writer, key string, fieldStruct *forms.FieldStructure) {
	//line views/templates/tables/table_view.qtpl:303
	qw422016.N().S(`
    <select id="`)
	//line views/templates/tables/table_view.qtpl:304
	qw422016.E().S(key)
	//line views/templates/tables/table_view.qtpl:304
	qw422016.N().S(`" name="`)
	//line views/templates/tables/table_view.qtpl:304
	qw422016.E().S(key)
	//line views/templates/tables/table_view.qtpl:304
	qw422016.N().S(`" onchange="return FilterIsModified( event, this);">
        <option selected>-</option>
        `)
	//line views/templates/tables/table_view.qtpl:306
	qw422016.N().S(fieldStruct.Html)
	//line views/templates/tables/table_view.qtpl:306
	qw422016.N().S(`
    </select>
`)
//line views/templates/tables/table_view.qtpl:308
}

//line views/templates/tables/table_view.qtpl:308
func writerenderFilterSelect(qq422016 qtio422016.Writer, key string, fieldStruct *forms.FieldStructure) {
	//line views/templates/tables/table_view.qtpl:308
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/tables/table_view.qtpl:308
	streamrenderFilterSelect(qw422016, key, fieldStruct)
	//line views/templates/tables/table_view.qtpl:308
	qt422016.ReleaseWriter(qw422016)
//line views/templates/tables/table_view.qtpl:308
}

//line views/templates/tables/table_view.qtpl:308
func renderFilterSelect(key string, fieldStruct *forms.FieldStructure) string {
	//line views/templates/tables/table_view.qtpl:308
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/tables/table_view.qtpl:308
	writerenderFilterSelect(qb422016, key, fieldStruct)
	//line views/templates/tables/table_view.qtpl:308
	qs422016 := string(qb422016.B)
	//line views/templates/tables/table_view.qtpl:308
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/tables/table_view.qtpl:308
	return qs422016
//line views/templates/tables/table_view.qtpl:308
}

//line views/templates/tables/table_view.qtpl:309
func streaminputFilterField(qw422016 *qt422016.Writer, key, nameTable string, fieldStruct *forms.FieldStructure) {
	//line views/templates/tables/table_view.qtpl:309
	qw422016.N().S(`
 <div title="`)
	//line views/templates/tables/table_view.qtpl:310
	qw422016.E().S(key)
	//line views/templates/tables/table_view.qtpl:310
	qw422016.N().S(`" class="td" style="`)
	//line views/templates/tables/table_view.qtpl:310
	qw422016.N().S(fieldStruct.CSSStyle)
	//line views/templates/tables/table_view.qtpl:310
	qw422016.N().S(`">
                        `)
	//line views/templates/tables/table_view.qtpl:311
	if key == "parent_id" {
		//line views/templates/tables/table_view.qtpl:311
		qw422016.N().S(`
                                `)
		//line views/templates/tables/table_view.qtpl:312
		fieldStruct.GetOptions(nameTable, "")

		//line views/templates/tables/table_view.qtpl:312
		qw422016.N().S(`
                                `)
		//line views/templates/tables/table_view.qtpl:313
		streamrenderFilterSelect(qw422016, key, fieldStruct)
		//line views/templates/tables/table_view.qtpl:313
		qw422016.N().S(`
                        `)
		//line views/templates/tables/table_view.qtpl:314
	} else if strings.HasPrefix(key, "id_") {
		//line views/templates/tables/table_view.qtpl:314
		qw422016.N().S(`
                                `)
		//line views/templates/tables/table_view.qtpl:315
		fieldStruct.GetOptions(key[3:], "")

		//line views/templates/tables/table_view.qtpl:315
		qw422016.N().S(`
                                `)
		//line views/templates/tables/table_view.qtpl:316
		streamrenderFilterSelect(qw422016, key, fieldStruct)
		//line views/templates/tables/table_view.qtpl:316
		qw422016.N().S(`
                        `)
		//line views/templates/tables/table_view.qtpl:317
	} else {
		//line views/templates/tables/table_view.qtpl:317
		qw422016.N().S(`
                            `)
		//line views/templates/tables/table_view.qtpl:318
		switch fieldStruct.DATA_TYPE {
		//line views/templates/tables/table_view.qtpl:319
		case "tinyint":
			//line views/templates/tables/table_view.qtpl:319
			qw422016.N().S(`
                                    `)
			//line views/templates/tables/table_view.qtpl:320
			forms.StreamRenderCheckBox(qw422016, key, "1", "", 1, "", "", "", "")
			//line views/templates/tables/table_view.qtpl:320
			qw422016.N().S(`
                            `)
		//line views/templates/tables/table_view.qtpl:321
		case "enum":
			//line views/templates/tables/table_view.qtpl:321
			qw422016.N().S(`
                                `)
			//line views/templates/tables/table_view.qtpl:322
			t := fieldStruct.RenderEnum(key, "", "", "", "")

			//line views/templates/tables/table_view.qtpl:322
			qw422016.N().S(`
                                `)
			//line views/templates/tables/table_view.qtpl:323
			qw422016.N().S(t)
			//line views/templates/tables/table_view.qtpl:323
			qw422016.N().S(`
                            `)
		//line views/templates/tables/table_view.qtpl:324
		case "set":
			//line views/templates/tables/table_view.qtpl:324
			qw422016.N().S(`
                                `)
			//line views/templates/tables/table_view.qtpl:325
			t := fieldStruct.RenderSet(key, "", "", "", "")

			//line views/templates/tables/table_view.qtpl:325
			qw422016.N().S(`
                                `)
			//line views/templates/tables/table_view.qtpl:326
			qw422016.N().S(t)
			//line views/templates/tables/table_view.qtpl:326
			qw422016.N().S(`
               `)
		//line views/templates/tables/table_view.qtpl:327
		default:
			//line views/templates/tables/table_view.qtpl:327
			qw422016.N().S(`
                        <input id="`)
			//line views/templates/tables/table_view.qtpl:328
			qw422016.E().S(key)
			//line views/templates/tables/table_view.qtpl:328
			qw422016.N().S(`" name="`)
			//line views/templates/tables/table_view.qtpl:328
			qw422016.E().S(key)
			//line views/templates/tables/table_view.qtpl:328
			qw422016.N().S(`" type=

                        `)
			//line views/templates/tables/table_view.qtpl:330
			if fieldStruct.InputType > "" {
				//line views/templates/tables/table_view.qtpl:330
				qw422016.N().S(`
                            "`)
				//line views/templates/tables/table_view.qtpl:331
				qw422016.E().S(fieldStruct.InputType)
				//line views/templates/tables/table_view.qtpl:331
				qw422016.N().S(`"
                        `)
				//line views/templates/tables/table_view.qtpl:332
			} else if fieldStruct.DATA_TYPE == "int" || fieldStruct.DATA_TYPE == "double" {
				//line views/templates/tables/table_view.qtpl:332
				qw422016.N().S(`
                            "number" `)
				//line views/templates/tables/table_view.qtpl:333
				if strings.Contains(fieldStruct.COLUMN_TYPE, "unsigned") {
					//line views/templates/tables/table_view.qtpl:333
					qw422016.N().S(`min="0"`)
					//line views/templates/tables/table_view.qtpl:333
				}
				//line views/templates/tables/table_view.qtpl:333
				qw422016.N().S(`
                        `)
				//line views/templates/tables/table_view.qtpl:334
			} else if fieldStruct.DATA_TYPE == "date" {
				//line views/templates/tables/table_view.qtpl:334
				qw422016.N().S(`
                            "date"  `)
				//line views/templates/tables/table_view.qtpl:335
				fieldStruct.StreamRenderDateAttributtes(qw422016)
				//line views/templates/tables/table_view.qtpl:335
				qw422016.N().S(`
                        `)
				//line views/templates/tables/table_view.qtpl:336
			} else if fieldStruct.DATA_TYPE == "datetime" {
				//line views/templates/tables/table_view.qtpl:336
				qw422016.N().S(`
                            "datetime" `)
				//line views/templates/tables/table_view.qtpl:337
				fieldStruct.StreamRenderDateAttributtes(qw422016)
				//line views/templates/tables/table_view.qtpl:337
				qw422016.N().S(`
                        `)
				//line views/templates/tables/table_view.qtpl:338
			} else if strings.Contains(key, "email") {
				//line views/templates/tables/table_view.qtpl:338
				qw422016.N().S(`
                            "email"
                        `)
				//line views/templates/tables/table_view.qtpl:340
			} else {
				//line views/templates/tables/table_view.qtpl:340
				qw422016.N().S(`
                            "text"
                               `)
				//line views/templates/tables/table_view.qtpl:342
				if fieldStruct.CHARACTER_MAXIMUM_LENGTH > 0 {
					//line views/templates/tables/table_view.qtpl:342
					qw422016.N().S(`
                                    maxlength="`)
					//line views/templates/tables/table_view.qtpl:343
					qw422016.N().D(fieldStruct.CHARACTER_MAXIMUM_LENGTH)
					//line views/templates/tables/table_view.qtpl:343
					qw422016.N().S(`"
                               `)
					//line views/templates/tables/table_view.qtpl:344
				}
				//line views/templates/tables/table_view.qtpl:344
				qw422016.N().S(`
                        `)
				//line views/templates/tables/table_view.qtpl:345
			}
			//line views/templates/tables/table_view.qtpl:345
			qw422016.N().S(`
                        onkeyup="return FilterIsModified( event, this);"
                        />
               `)
			//line views/templates/tables/table_view.qtpl:348
		}
		//line views/templates/tables/table_view.qtpl:348
		qw422016.N().S(`
        `)
		//line views/templates/tables/table_view.qtpl:349
	}
	//line views/templates/tables/table_view.qtpl:349
	qw422016.N().S(`
  </div>
`)
//line views/templates/tables/table_view.qtpl:351
}

//line views/templates/tables/table_view.qtpl:351
func writeinputFilterField(qq422016 qtio422016.Writer, key, nameTable string, fieldStruct *forms.FieldStructure) {
	//line views/templates/tables/table_view.qtpl:351
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line views/templates/tables/table_view.qtpl:351
	streaminputFilterField(qw422016, key, nameTable, fieldStruct)
	//line views/templates/tables/table_view.qtpl:351
	qt422016.ReleaseWriter(qw422016)
//line views/templates/tables/table_view.qtpl:351
}

//line views/templates/tables/table_view.qtpl:351
func inputFilterField(key, nameTable string, fieldStruct *forms.FieldStructure) string {
	//line views/templates/tables/table_view.qtpl:351
	qb422016 := qt422016.AcquireByteBuffer()
	//line views/templates/tables/table_view.qtpl:351
	writeinputFilterField(qb422016, key, nameTable, fieldStruct)
	//line views/templates/tables/table_view.qtpl:351
	qs422016 := string(qb422016.B)
	//line views/templates/tables/table_view.qtpl:351
	qt422016.ReleaseByteBuffer(qb422016)
	//line views/templates/tables/table_view.qtpl:351
	return qs422016
//line views/templates/tables/table_view.qtpl:351
}
