/*
 * Copyright (c) 2022. Author: Ruslan Bikchentaev. All rights reserved.
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file.
 * Першій пріватний програміст.
 */

// Code generated by qtc from "endpointTpl.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line endpointTpl.qtpl:2
package tpl

//line endpointTpl.qtpl:2
import (
	"fmt"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"

	"github.com/iancoleman/strcase"

	"github.com/ruslanBik4/dbEngine/dbEngine"
	"github.com/ruslanBik4/httpgo/apis"
)

//   interface of endpoint
//   // Code generated by httpgo-gen-go. DO NOT EDIT.

//line endpointTpl.qtpl:16
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line endpointTpl.qtpl:16
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line endpointTpl.qtpl:17
type EndpointTpl struct {
	apis.ApiRoute
	dbEngine.Table
}

func NewEndpointTpl(route apis.ApiRoute, table dbEngine.Table) *EndpointTpl {
	return &EndpointTpl{
		route,
		table,
	}
}

//line endpointTpl.qtpl:30
func streamparamName(qw422016 *qt422016.Writer, name string) {
//line endpointTpl.qtpl:31
	qw422016.N().S(cases.Title(language.English, cases.NoLower).String(strcase.ToCamel(name)))
//line endpointTpl.qtpl:32
}

//line endpointTpl.qtpl:32
func writeparamName(qq422016 qtio422016.Writer, name string) {
//line endpointTpl.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line endpointTpl.qtpl:32
	streamparamName(qw422016, name)
//line endpointTpl.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line endpointTpl.qtpl:32
}

//line endpointTpl.qtpl:32
func paramName(name string) string {
//line endpointTpl.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line endpointTpl.qtpl:32
	writeparamName(qb422016, name)
//line endpointTpl.qtpl:32
	qs422016 := string(qb422016.B)
//line endpointTpl.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line endpointTpl.qtpl:32
	return qs422016
//line endpointTpl.qtpl:32
}

//line endpointTpl.qtpl:33
func (e *EndpointTpl) streamdtoName(qw422016 *qt422016.Writer) {
//line endpointTpl.qtpl:34
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:34
	qw422016.N().S(`Fields`)
//line endpointTpl.qtpl:35
}

//line endpointTpl.qtpl:35
func (e *EndpointTpl) writedtoName(qq422016 qtio422016.Writer) {
//line endpointTpl.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line endpointTpl.qtpl:35
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line endpointTpl.qtpl:35
}

//line endpointTpl.qtpl:35
func (e *EndpointTpl) dtoName() string {
//line endpointTpl.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line endpointTpl.qtpl:35
	e.writedtoName(qb422016)
//line endpointTpl.qtpl:35
	qs422016 := string(qb422016.B)
//line endpointTpl.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line endpointTpl.qtpl:35
	return qs422016
//line endpointTpl.qtpl:35
}

//line endpointTpl.qtpl:37
func (e *EndpointTpl) StreamNameRoutes(qw422016 *qt422016.Writer) {
//line endpointTpl.qtpl:38
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:38
	qw422016.N().S(`Routes`)
//line endpointTpl.qtpl:39
}

//line endpointTpl.qtpl:39
func (e *EndpointTpl) WriteNameRoutes(qq422016 qtio422016.Writer) {
//line endpointTpl.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line endpointTpl.qtpl:39
	e.StreamNameRoutes(qw422016)
//line endpointTpl.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line endpointTpl.qtpl:39
}

//line endpointTpl.qtpl:39
func (e *EndpointTpl) NameRoutes() string {
//line endpointTpl.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
//line endpointTpl.qtpl:39
	e.WriteNameRoutes(qb422016)
//line endpointTpl.qtpl:39
	qs422016 := string(qb422016.B)
//line endpointTpl.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
//line endpointTpl.qtpl:39
	return qs422016
//line endpointTpl.qtpl:39
}

//line endpointTpl.qtpl:43
func (e *EndpointTpl) StreamApisFile(qw422016 *qt422016.Writer) {
//line endpointTpl.qtpl:43
	qw422016.N().S(`
type
    `)
//line endpointTpl.qtpl:45
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:45
	qw422016.N().S(` struct {
       `)
//line endpointTpl.qtpl:46
	for _, param := range e.Params {
//line endpointTpl.qtpl:46
		qw422016.N().S(` `)
//line endpointTpl.qtpl:47
		qw422016.N().S(fmt.Sprintf("%-21s", paramName(param.Name)))
//line endpointTpl.qtpl:47
		qw422016.N().S(` `)
//line endpointTpl.qtpl:48
		if t, ok := (param.Type).(apis.TypeInParam); ok && t.DTO != nil {
//line endpointTpl.qtpl:48
			qw422016.N().S(` `)
//line endpointTpl.qtpl:49
			qw422016.N().S(fmt.Sprintf("%T", t.DTO))
//line endpointTpl.qtpl:49
			qw422016.N().S(` `)
//line endpointTpl.qtpl:50
		} else {
//line endpointTpl.qtpl:50
			qw422016.N().S(` `)
//line endpointTpl.qtpl:51
			qw422016.N().S(param.Type.String())
//line endpointTpl.qtpl:51
			qw422016.N().S(` `)
//line endpointTpl.qtpl:52
		}
//line endpointTpl.qtpl:52
		qw422016.N().S(` `)
//line endpointTpl.qtpl:53
		qw422016.N().S(`       `)
//line endpointTpl.qtpl:53
		qw422016.N().S("`")
//line endpointTpl.qtpl:53
		qw422016.N().S(`json:"`)
//line endpointTpl.qtpl:53
		qw422016.E().S(param.Name)
//line endpointTpl.qtpl:53
		qw422016.N().S(`"`)
//line endpointTpl.qtpl:53
		qw422016.N().S("`")
//line endpointTpl.qtpl:53
		qw422016.N().S(`
       `)
//line endpointTpl.qtpl:54
	}
//line endpointTpl.qtpl:54
	qw422016.N().S(` Limit                int     `)
//line endpointTpl.qtpl:54
	qw422016.N().S("`")
//line endpointTpl.qtpl:54
	qw422016.N().S(`json:"id_photos"`)
//line endpointTpl.qtpl:54
	qw422016.N().S("`")
//line endpointTpl.qtpl:54
	qw422016.N().S(`
     }
// GetValue implement httpgo.RouteDTO interface
func (r *`)
//line endpointTpl.qtpl:57
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:57
	qw422016.N().S(`) GetValue() interface{} {
	return r
}
// NewValue implement httpgo.RouteDTO interface
func (r *`)
//line endpointTpl.qtpl:61
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:61
	qw422016.N().S(`) NewValue() interface{} {
	return `)
//line endpointTpl.qtpl:62
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:62
	qw422016.N().S(`{}
}
// CheckParams implement CheckDTO interface, put each params into user value on context
func (r *`)
//line endpointTpl.qtpl:65
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:65
	qw422016.N().S(`) CheckParams(ctx *fasthttp.RequestCtx, badParams map[string]string) bool {
	val := fastjson.MustParseBytes(ctx.Request.Body())
`)
//line endpointTpl.qtpl:67
	for _, param := range e.Params {
//line endpointTpl.qtpl:67
		qw422016.N().S(`	if val.Exists("`)
//line endpointTpl.qtpl:68
		qw422016.E().S(param.Name)
//line endpointTpl.qtpl:68
		qw422016.N().S(`") {
		ctx.SetUserValue("`)
//line endpointTpl.qtpl:69
		qw422016.E().S(param.Name)
//line endpointTpl.qtpl:69
		qw422016.N().S(`", r.`)
//line endpointTpl.qtpl:69
		streamparamName(qw422016, param.Name)
//line endpointTpl.qtpl:69
		qw422016.N().S(`)
	}
`)
//line endpointTpl.qtpl:71
	}
//line endpointTpl.qtpl:71
	qw422016.N().S(`	return true
}
// RefColValue return referral of column
func (r *`)
//line endpointTpl.qtpl:75
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:75
	qw422016.N().S(`) RefColValue(name string) interface{}{
	switch name {
`)
//line endpointTpl.qtpl:77
	for _, param := range e.Params {
//line endpointTpl.qtpl:77
		qw422016.N().S(`	case "`)
//line endpointTpl.qtpl:78
		qw422016.E().S(param.Name)
//line endpointTpl.qtpl:78
		qw422016.N().S(`":
        return &r.`)
//line endpointTpl.qtpl:79
		qw422016.N().S(paramName(param.Name))
//line endpointTpl.qtpl:79
		qw422016.N().S(`
`)
//line endpointTpl.qtpl:80
	}
//line endpointTpl.qtpl:80
	qw422016.N().S(`   	default:
		logs.ErrorLog(errors.Errorf("unknown column name '%s'", name))
		return nil
	}
}
// ColValue return value of column
func (r *`)
//line endpointTpl.qtpl:87
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:87
	qw422016.N().S(`) ColValue(name string) interface{}{
	switch name {
`)
//line endpointTpl.qtpl:89
	for _, param := range e.Params {
//line endpointTpl.qtpl:89
		qw422016.N().S(`	case "`)
//line endpointTpl.qtpl:90
		qw422016.E().S(param.Name)
//line endpointTpl.qtpl:90
		qw422016.N().S(`":
        return r.`)
//line endpointTpl.qtpl:91
		streamparamName(qw422016, param.Name)
//line endpointTpl.qtpl:91
		qw422016.N().S(`
`)
//line endpointTpl.qtpl:92
	}
//line endpointTpl.qtpl:92
	qw422016.N().S(`   	default:
		logs.ErrorLog(errors.Errorf("unknown column name '%s'", name))
		return nil
	}
}
// GetFields implement dbEngine.RowScanner interface
func (r *`)
//line endpointTpl.qtpl:99
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:99
	qw422016.N().S(`) GetFields(columns []dbEngine.Column) []interface{} {
	v := make([]interface{}, len(columns))
	for i, col := range columns {
		v[i] = r.RefColValue( col.Name() )
	}

	return v
}

// NewValue implement httpgo.RouteDTO interface
func (r *`)
//line endpointTpl.qtpl:109
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:109
	qw422016.N().S(`) SqlOptions(ctx *fasthttp.RequestCtx, isWhere bool) []dbEngine.BuildSqlOptions {
        args := make([]interface{}, 0, `)
//line endpointTpl.qtpl:110
	qw422016.N().D(len(e.Params))
//line endpointTpl.qtpl:110
	qw422016.N().S(`)
        colNames := make([]string, 0, `)
//line endpointTpl.qtpl:111
	qw422016.N().D(len(e.Params))
//line endpointTpl.qtpl:111
	qw422016.N().S(`)
        `)
//line endpointTpl.qtpl:112
	for _, param := range e.Params {
//line endpointTpl.qtpl:112
		qw422016.N().S(`
            if v := ctx.UserValue( "`)
//line endpointTpl.qtpl:113
		qw422016.E().S(param.Name)
//line endpointTpl.qtpl:113
		qw422016.N().S(`" ); v != nil {
                args = append(args, v)
                colNames = append(colNames, "`)
//line endpointTpl.qtpl:115
		qw422016.E().S(param.Name)
//line endpointTpl.qtpl:115
		qw422016.N().S(`")
            }
        `)
//line endpointTpl.qtpl:117
	}
//line endpointTpl.qtpl:117
	qw422016.N().S(`

	res := []dbEngine.BuildSqlOptions{
		dbEngine.Args(args...),
	}
	if isWhere {
		res = append(res, dbEngine.WhereForSelect(colNames...) )
	} else {
		res = append(res, dbEngine.Columns(colNames...) )
	}

	if r.Limit > 0 {
		res = append(res, dbEngine.FetchOnlyRows(r.Limit))
	}

	return res
}
var
	`)
//line endpointTpl.qtpl:135
	e.StreamNameRoutes(qw422016)
//line endpointTpl.qtpl:135
	qw422016.N().S(` = apis.ApiRoutes{
		"/table/`)
//line endpointTpl.qtpl:136
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:136
	qw422016.N().S(`/get": {
			Fnc:    Handle`)
//line endpointTpl.qtpl:137
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:137
	qw422016.N().S(`Get,
			Desc:   "get data of table '`)
//line endpointTpl.qtpl:138
	qw422016.E().S(e.Name())
//line endpointTpl.qtpl:138
	qw422016.N().S(`' (`)
//line endpointTpl.qtpl:138
	qw422016.E().S(e.Desc)
//line endpointTpl.qtpl:138
	qw422016.N().S(`)",
			DTO:    &`)
//line endpointTpl.qtpl:139
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:139
	qw422016.N().S(`{},
			Method: apis.GET,
			NeedAuth: true,
		},
		"/table/`)
//line endpointTpl.qtpl:143
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:143
	qw422016.N().S(`/put": {
			Fnc:    Handle`)
//line endpointTpl.qtpl:144
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:144
	qw422016.N().S(`Put,
			Desc:   "`)
//line endpointTpl.qtpl:145
	qw422016.E().S(e.Desc)
//line endpointTpl.qtpl:145
	qw422016.N().S(`",
			DTO:    &`)
//line endpointTpl.qtpl:146
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:146
	qw422016.N().S(`{},
			Method: apis.POST,
			NeedAuth: true,
		},
		"/table/`)
//line endpointTpl.qtpl:150
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:150
	qw422016.N().S(`/update": {
			Fnc:    Handle`)
//line endpointTpl.qtpl:151
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:151
	qw422016.N().S(`Update,
			Desc:   "`)
//line endpointTpl.qtpl:152
	qw422016.E().S(e.Desc)
//line endpointTpl.qtpl:152
	qw422016.N().S(`",
			DTO:    &`)
//line endpointTpl.qtpl:153
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:153
	qw422016.N().S(`{},
			Method: apis.POST,
			NeedAuth: true,
		},
		"/table/`)
//line endpointTpl.qtpl:157
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:157
	qw422016.N().S(`/form": {
			Fnc:    Handle`)
//line endpointTpl.qtpl:158
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:158
	qw422016.N().S(`Form,
			Desc:   "get form for insert/update data into '`)
//line endpointTpl.qtpl:159
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:159
	qw422016.N().S(`' (`)
//line endpointTpl.qtpl:159
	qw422016.E().S(e.Desc)
//line endpointTpl.qtpl:159
	qw422016.N().S(`)",
			DTO:    &`)
//line endpointTpl.qtpl:160
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:160
	qw422016.N().S(`{},
			Method: apis.GET,
			Params: apis.BasicParams,
			NeedAuth: true,
			WithCors: true,
		},
	}

func Get`)
//line endpointTpl.qtpl:168
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:168
	qw422016.N().S(`Params(ctx *fasthttp.RequestCtx) (dbEngine.Table, *`)
//line endpointTpl.qtpl:168
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:168
	qw422016.N().S(`, error) {
    DB, ok := ctx.UserValue("DB").(*dbEngine.DB)
    if !ok {
        return nil, nil, dbEngine.ErrDBNotFound
    }

    table, ok := DB.Tables["`)
//line endpointTpl.qtpl:174
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:174
	qw422016.N().S(`"]
    if !ok {
        return nil, nil, dbEngine.ErrNotFoundTable{Table: "`)
//line endpointTpl.qtpl:176
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:176
	qw422016.N().S(`"}
    }

    params, ok := ctx.UserValue(apis.JSONParams).(*`)
//line endpointTpl.qtpl:179
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:179
	qw422016.N().S(`)
    if !ok {
        return nil, nil, apis.ErrWrongParamsList
    }

    return table, params, nil
}

func Handle`)
//line endpointTpl.qtpl:187
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:187
	qw422016.N().S(`Get(ctx *fasthttp.RequestCtx) (interface{}, error) {
    table, params, err := Get`)
//line endpointTpl.qtpl:188
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:188
	qw422016.N().S(`Params(ctx)
    if err != nil {
        return nil, errors.Wrap(err, "Handle`)
//line endpointTpl.qtpl:190
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:190
	qw422016.N().S(`Get")
    }

    res := make([]`)
//line endpointTpl.qtpl:193
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:193
	qw422016.N().S(`, 0)
    buf := &`)
//line endpointTpl.qtpl:194
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:194
	qw422016.N().S(`{}
    err = table.SelectAndScanEach(ctx,
        func() error {
            res = append(res, *buf)

            return nil
        },
        buf,
        params.SqlOptions(ctx, true)...
    )
    if err != nil {
        return nil, errors.Wrap(err, "Handle`)
//line endpointTpl.qtpl:205
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:205
	qw422016.N().S(`Get")
    }

    if len(res) == 0 {
        ctx.SetStatusCode(fasthttp.StatusNoContent)
        return nil, nil
    }

    return res, nil
}

func Handle`)
//line endpointTpl.qtpl:216
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:216
	qw422016.N().S(`Put(ctx *fasthttp.RequestCtx) (interface{}, error) {
    table, params, err := Get`)
//line endpointTpl.qtpl:217
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:217
	qw422016.N().S(`Params(ctx)
    if err != nil {
        return nil, errors.Wrap(err, "Handle`)
//line endpointTpl.qtpl:219
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:219
	qw422016.N().S(`Put")
    }

		id, err := table.Insert(ctx, params.SqlOptions(ctx, false)...)
		if err != nil {
			return crud.CreateErrResult(err)
		}

		return crud.RenderCreatedResult(ctx, id, bytes.NewBufferString(""), nil, "/table/`)
//line endpointTpl.qtpl:227
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:227
	qw422016.N().S(`/put")
}

func Handle`)
//line endpointTpl.qtpl:230
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:230
	qw422016.N().S(`Update(ctx *fasthttp.RequestCtx) (interface{}, error) {
    table, params, err := Get`)
//line endpointTpl.qtpl:231
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:231
	qw422016.N().S(`Params(ctx)
    if err != nil {
        return nil, errors.Wrap(err, "Handle`)
//line endpointTpl.qtpl:233
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:233
	qw422016.N().S(`Update")
    }

	badParams := make(map[string]string, 0)
	columns := table.Columns()
	priColumns := make([]string, 0)
    args := make([]interface{}, 0, len(columns))
    colSel := make([]string, 0, len(columns))
	buf := bytes.NewBufferString("")
    for _, col := range columns {
        name := col.Name()
        arg := ctx.UserValue(name)
        if col.Primary() {

			if arg == nil {
				badParams[name] = "required params"
                continue
			}
            if arg := ctx.UserValue("new." + name); arg != nil {
                colSel = append(colSel, name)
                args = append(args, arg)
                _, err := fmt.Fprintf(buf, " %v", arg)
                if err != nil {
                    return nil, err
                }
            }
            priColumns = append(priColumns, name)
            continue
        }
        if arg == nil {
            continue
        }

        crud.AddColumnAndValue(name, table, arg, args, colSel, buf, badParams)
    }

    for _, name := range priColumns {
        args = append(args, ctx.UserValue(name))
    }

    i, err := table.Update(ctx,
        dbEngine.ColumnsForSelect(colSel...),
        dbEngine.WhereForSelect(priColumns...),
        dbEngine.ArgsForSelect(args...),
    )
    if err != nil {
        return nil, err
    }

    if i <= 0 {
        logs.DebugLog(colSel, priColumns)
        logs.DebugLog(args)
        return map[string]string{"update": fmt.Sprintf("%d inserted for request %+v", i, params)}, apis.ErrWrongParamsList
    }

    return crud.RenderAcceptedResult(ctx, colSel, buf, "/table/`)
//line endpointTpl.qtpl:288
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:288
	qw422016.N().S(`/update")
}

func Handle`)
//line endpointTpl.qtpl:291
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:291
	qw422016.N().S(`Form(ctx *fasthttp.RequestCtx) (interface{}, error) {
    table, params, err := Get`)
//line endpointTpl.qtpl:292
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:292
	qw422016.N().S(`Params(ctx)
    if err != nil {
        return nil, errors.Wrap(err, "Handle`)
//line endpointTpl.qtpl:294
	streamparamName(qw422016, e.Name())
//line endpointTpl.qtpl:294
	qw422016.N().S(`Form")
    }

    record := `)
//line endpointTpl.qtpl:297
	e.streamdtoName(qw422016)
//line endpointTpl.qtpl:297
	qw422016.N().S(`{}
    err = table.SelectOneAndScan(ctx,
        &record,
        params.SqlOptions(ctx, true)...
    )
    if err != nil {
        return nil, errors.Wrap(err, "")
    }

		// we must copy colsTable into local array
		f := forms.FormField{
			Title:       "`)
//line endpointTpl.qtpl:308
	qw422016.E().S(e.Table.Comment())
//line endpointTpl.qtpl:308
	qw422016.N().S(`",
			Action:      "/table/`)
//line endpointTpl.qtpl:309
	qw422016.E().S(e.Table.Name())
//line endpointTpl.qtpl:309
	qw422016.N().S(`/",
			Method:      "POST",
			Description: "",
		}

		colDecors := make([]*forms.ColumnDecor, 0)

		columns := table.Columns()

	priColumns := make([]string, 0)
	buf := bytes.NewBufferString("")
   for _, col := range columns {
        name := col.Name()
        if col.Primary() {

		 /* 	if arg == nil {
				badParams[name] = "required params"
                continue
			}
          if arg := ctx.UserValue("new." + name); arg != nil {
                colSel = append(colSel, name)
                args = append(args, arg)
                _, err := fmt.Fprintf(buf, " %v", arg)
                if err != nil {
                    return nil, err
                }
            }
         */   priColumns = append(priColumns, name)
            continue
        }
				if !(col.AutoIncrement() || col.Name() == "id" ||
					strings.Contains(col.Comment(), " (read_only)")) {

					colDec := forms.NewColumnDecor(col, nil)
					colDec.IsDisabled = colDec.IsReadOnly && !(colDec.IsHidden)
					colDec.IsSlice = strings.HasPrefix(col.Type(), "_")
					colDec.Value = nil

					if col.Primary() {
						colDec.IsHidden = true
						colDec.InputType = "hidden"
					} else if col.Type() == "text" {
						colDec.InputType = "textarea"
					} else if col.Name() == "id_photos" {
						colDec.InputType = "attachment"
					} else if col.Name() == "memo" {
						colDec.InputType = "markdown"
					}
					colDecors = append(colDecors, colDec)
				}
    }

			f.Action += "/update"

    		lang, ok := ctx.UserValue(apis.ParamsLang.Name).(string)
    		if ok {
    			colDecors = append(colDecors, &forms.ColumnDecor{
    				Column:      dbEngine.NewStringColumn("lang", "lang", true),
    				IsHidden:    true,
    				InputType:   "hidden",
    				PatternList: nil,
    				Value:       lang,
    			})
    		}

 		btnList := []forms.Button{
 			{ButtonType: "submit", Title: "Insert", Position: true},
 			{ButtonType: "reset", Title: "Clear", Position: false},
 		}

   		blocks := []forms.BlockColumns{
    			{
    				Buttons:     btnList,
    				Columns:     colDecors,
    				Id:          1,
    				Title:       "",
    				Description: "",
    			},
    		}

    		_, ok = ctx.UserValue(apis.ParamsHTML.Name).(bool)
    		if !ok {
    			views.WriteJSONHeaders(ctx)
    		}

    		if f.Description == "" {
    			f.Description = "Input data for " + table.Comment()
    		}
    		f.WriteRenderForm(
    			ctx.Response.BodyWriter(),
    			ok, // && isHtml,
    			blocks...)

    		return nil, nil

}
`)
//line endpointTpl.qtpl:405
}

//line endpointTpl.qtpl:405
func (e *EndpointTpl) WriteApisFile(qq422016 qtio422016.Writer) {
//line endpointTpl.qtpl:405
	qw422016 := qt422016.AcquireWriter(qq422016)
//line endpointTpl.qtpl:405
	e.StreamApisFile(qw422016)
//line endpointTpl.qtpl:405
	qt422016.ReleaseWriter(qw422016)
//line endpointTpl.qtpl:405
}

//line endpointTpl.qtpl:405
func (e *EndpointTpl) ApisFile() string {
//line endpointTpl.qtpl:405
	qb422016 := qt422016.AcquireByteBuffer()
//line endpointTpl.qtpl:405
	e.WriteApisFile(qb422016)
//line endpointTpl.qtpl:405
	qs422016 := string(qb422016.B)
//line endpointTpl.qtpl:405
	qt422016.ReleaseByteBuffer(qb422016)
//line endpointTpl.qtpl:405
	return qs422016
//line endpointTpl.qtpl:405
}
