// Code generated by qtc from "table_row.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/templates/system/routeTable/table_row.qtpl:1
package routeTable

//line views/templates/system/routeTable/table_row.qtpl:1
import (
	"time"

	"github.com/ruslanBik4/dbEngine/dbEngine"
	"github.com/ruslanBik4/httpgo/views/templates/json"
)

//line views/templates/system/routeTable/table_row.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/templates/system/routeTable/table_row.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/templates/system/routeTable/table_row.qtpl:8
func StreamTableRow(qw422016 *qt422016.Writer, columns []dbEngine.Column, rows [][]interface{}) {
//line views/templates/system/routeTable/table_row.qtpl:8
	qw422016.N().S(`
<style>
`)
//line views/templates/system/routeTable/table_row.qtpl:10
	StreamTableCSS(qw422016)
//line views/templates/system/routeTable/table_row.qtpl:10
	qw422016.N().S(`
`)
//line views/templates/system/routeTable/table_row.qtpl:12
	colLen := make([]int, len(columns))
	allWidth := 0
	for i, col := range columns {
		colLen[i] = len(col.Name())
	}

//line views/templates/system/routeTable/table_row.qtpl:17
	qw422016.N().S(`
</style>
<div class="usr-table  table-custom">
    <div class="usr-table-header">
        <div class="usr-table__t-head  usr-table-row">
        `)
//line views/templates/system/routeTable/table_row.qtpl:22
	for i, col := range columns {
//line views/templates/system/routeTable/table_row.qtpl:22
		qw422016.N().S(`
            <div class="usr-table-col  table-col-`)
//line views/templates/system/routeTable/table_row.qtpl:23
		qw422016.N().D(i)
//line views/templates/system/routeTable/table_row.qtpl:23
		qw422016.N().S(`" a=`)
//line views/templates/system/routeTable/table_row.qtpl:23
		qw422016.N().D(i)
//line views/templates/system/routeTable/table_row.qtpl:23
		qw422016.N().S(`>
                `)
//line views/templates/system/routeTable/table_row.qtpl:24
		qw422016.E().S(col.Name())
//line views/templates/system/routeTable/table_row.qtpl:24
		qw422016.N().S(`
            </div>
        `)
//line views/templates/system/routeTable/table_row.qtpl:26
	}
//line views/templates/system/routeTable/table_row.qtpl:26
	qw422016.N().S(`
        </div>

        <div class="usr-table__filter  usr-table-row">
         `)
//line views/templates/system/routeTable/table_row.qtpl:30
	for i, col := range columns {
//line views/templates/system/routeTable/table_row.qtpl:30
		qw422016.N().S(`
           <div class="usr-table-col table-col-`)
//line views/templates/system/routeTable/table_row.qtpl:31
		qw422016.N().D(i)
//line views/templates/system/routeTable/table_row.qtpl:31
		qw422016.N().S(`">
                <div class="filt-arrow" style="word-break: break-word;">

                    <a class="filt-arrow__link arrow-bottom" href="#`)
//line views/templates/system/routeTable/table_row.qtpl:34
		qw422016.E().S(col.Name())
//line views/templates/system/routeTable/table_row.qtpl:34
		qw422016.N().S(`" title="`)
//line views/templates/system/routeTable/table_row.qtpl:34
		qw422016.E().S(col.Type())
//line views/templates/system/routeTable/table_row.qtpl:34
		qw422016.N().S(`">
                        `)
//line views/templates/system/routeTable/table_row.qtpl:35
		qw422016.E().S(col.Comment())
//line views/templates/system/routeTable/table_row.qtpl:35
		qw422016.N().S(`
                    </a>
                </div>
            </div>
          `)
//line views/templates/system/routeTable/table_row.qtpl:39
	}
//line views/templates/system/routeTable/table_row.qtpl:39
	qw422016.N().S(`
         </div>
    </div>

    <div class="usr-table-content">
        <div class="usr-table-content-scroll">
            <div class="usr-table-row-cont">

               `)
//line views/templates/system/routeTable/table_row.qtpl:47
	for _, row := range rows {
//line views/templates/system/routeTable/table_row.qtpl:47
		qw422016.N().S(`

                    <div  class="usr-table-row">

                    `)
//line views/templates/system/routeTable/table_row.qtpl:51
		for i, column := range columns {
//line views/templates/system/routeTable/table_row.qtpl:51
			qw422016.N().S(`
                        <div class="usr-table-col  table-col-`)
//line views/templates/system/routeTable/table_row.qtpl:52
			qw422016.N().D(i)
//line views/templates/system/routeTable/table_row.qtpl:52
			qw422016.N().S(`">
                            `)
//line views/templates/system/routeTable/table_row.qtpl:53
			switch val := row[i].(type) {
//line views/templates/system/routeTable/table_row.qtpl:54
			case time.Time:
//line views/templates/system/routeTable/table_row.qtpl:54
				qw422016.N().S(`  `)
//line views/templates/system/routeTable/table_row.qtpl:54
				qw422016.E().S(val.Format("2006-01-02"))
//line views/templates/system/routeTable/table_row.qtpl:54
				qw422016.N().S(`
                            `)
//line views/templates/system/routeTable/table_row.qtpl:55
			case string:
//line views/templates/system/routeTable/table_row.qtpl:55
				qw422016.N().S(`
                              `)
//line views/templates/system/routeTable/table_row.qtpl:56
				qw422016.N().S(val)
//line views/templates/system/routeTable/table_row.qtpl:56
				qw422016.N().S(`
                              `)
//line views/templates/system/routeTable/table_row.qtpl:58
				if len(val) > colLen[i] && (column.Name() != "id") {
					colLen[i] = len(val)
				}

//line views/templates/system/routeTable/table_row.qtpl:61
				qw422016.N().S(`
                            `)
//line views/templates/system/routeTable/table_row.qtpl:62
			case float32:
//line views/templates/system/routeTable/table_row.qtpl:62
				qw422016.N().S(`   `)
//line views/templates/system/routeTable/table_row.qtpl:62
				qw422016.N().V(val)
//line views/templates/system/routeTable/table_row.qtpl:62
				qw422016.N().S(`
                            `)
//line views/templates/system/routeTable/table_row.qtpl:63
			case float64:
//line views/templates/system/routeTable/table_row.qtpl:63
				qw422016.N().S(`   `)
//line views/templates/system/routeTable/table_row.qtpl:63
				qw422016.N().FPrec(val, 2)
//line views/templates/system/routeTable/table_row.qtpl:63
				qw422016.N().S(`
                            `)
//line views/templates/system/routeTable/table_row.qtpl:64
			default:
//line views/templates/system/routeTable/table_row.qtpl:64
				qw422016.N().S(`
                              `)
//line views/templates/system/routeTable/table_row.qtpl:65
				if r, ok := val.([]string); ok {
//line views/templates/system/routeTable/table_row.qtpl:65
					qw422016.N().S(`
                                {
                                 `)
//line views/templates/system/routeTable/table_row.qtpl:67
					for _, str := range r {
//line views/templates/system/routeTable/table_row.qtpl:67
						qw422016.N().S(`
                                  <p>`)
//line views/templates/system/routeTable/table_row.qtpl:68
						qw422016.N().S(str)
//line views/templates/system/routeTable/table_row.qtpl:68
						qw422016.N().S(` </p>
                               `)
//line views/templates/system/routeTable/table_row.qtpl:70
						if len(r) > colLen[i] {
							colLen[i] = len(r)
						}

//line views/templates/system/routeTable/table_row.qtpl:73
						qw422016.N().S(`
                               `)
//line views/templates/system/routeTable/table_row.qtpl:74
					}
//line views/templates/system/routeTable/table_row.qtpl:74
					qw422016.N().S(`
                               }
                             `)
//line views/templates/system/routeTable/table_row.qtpl:76
				} else if r, ok := val.([]interface{}); ok {
//line views/templates/system/routeTable/table_row.qtpl:76
					qw422016.N().S(`
                                 `)
//line views/templates/system/routeTable/table_row.qtpl:77
					for _, value := range r {
//line views/templates/system/routeTable/table_row.qtpl:77
						qw422016.N().S(`
                                  <p>{
                                    `)
//line views/templates/system/routeTable/table_row.qtpl:79
						if m, ok := value.(map[string]interface{}); ok {
//line views/templates/system/routeTable/table_row.qtpl:79
							qw422016.N().S(`
                                      `)
//line views/templates/system/routeTable/table_row.qtpl:80
							for key, value := range m {
//line views/templates/system/routeTable/table_row.qtpl:80
								qw422016.N().S(`
                                        <b>`)
//line views/templates/system/routeTable/table_row.qtpl:81
								qw422016.E().S(key)
//line views/templates/system/routeTable/table_row.qtpl:81
								qw422016.N().S(`</b>: `)
//line views/templates/system/routeTable/table_row.qtpl:81
								json.StreamElement(qw422016, value)
//line views/templates/system/routeTable/table_row.qtpl:81
								qw422016.N().S(`,
                                      `)
//line views/templates/system/routeTable/table_row.qtpl:82
							}
//line views/templates/system/routeTable/table_row.qtpl:82
							qw422016.N().S(`
                                    `)
//line views/templates/system/routeTable/table_row.qtpl:83
						} else {
//line views/templates/system/routeTable/table_row.qtpl:83
							qw422016.N().S(`
                                          `)
//line views/templates/system/routeTable/table_row.qtpl:84
							json.StreamElement(qw422016, value)
//line views/templates/system/routeTable/table_row.qtpl:84
							qw422016.N().S(`
                                    `)
//line views/templates/system/routeTable/table_row.qtpl:85
						}
//line views/templates/system/routeTable/table_row.qtpl:85
						qw422016.N().S(`
                                  } </p>
                                `)
//line views/templates/system/routeTable/table_row.qtpl:87
					}
//line views/templates/system/routeTable/table_row.qtpl:87
					qw422016.N().S(`
                              `)
//line views/templates/system/routeTable/table_row.qtpl:88
				} else {
//line views/templates/system/routeTable/table_row.qtpl:88
					qw422016.N().S(`
                                    `)
//line views/templates/system/routeTable/table_row.qtpl:89
					json.StreamElement(qw422016, row[i])
//line views/templates/system/routeTable/table_row.qtpl:89
					qw422016.N().S(`
                              `)
//line views/templates/system/routeTable/table_row.qtpl:90
				}
//line views/templates/system/routeTable/table_row.qtpl:90
				qw422016.N().S(`
                            `)
//line views/templates/system/routeTable/table_row.qtpl:91
			}
//line views/templates/system/routeTable/table_row.qtpl:91
			qw422016.N().S(`
                        </div>
                    `)
//line views/templates/system/routeTable/table_row.qtpl:93
		}
//line views/templates/system/routeTable/table_row.qtpl:93
		qw422016.N().S(`

                  </div>

                `)
//line views/templates/system/routeTable/table_row.qtpl:97
	}
//line views/templates/system/routeTable/table_row.qtpl:97
	qw422016.N().S(`

            </div>
        </div>
    </div>
</div>
<style>
`)
//line views/templates/system/routeTable/table_row.qtpl:104
	for i, cLen := range colLen {
//line views/templates/system/routeTable/table_row.qtpl:104
		qw422016.N().S(`
  `)
//line views/templates/system/routeTable/table_row.qtpl:106
		if cLen > 50 {
			cLen = 50
		}
		lSymb := 7
		allWidth += cLen * lSymb

//line views/templates/system/routeTable/table_row.qtpl:112
		qw422016.N().S(`
.table-col-`)
//line views/templates/system/routeTable/table_row.qtpl:113
		qw422016.N().D(i)
//line views/templates/system/routeTable/table_row.qtpl:113
		qw422016.N().S(`{
    width: `)
//line views/templates/system/routeTable/table_row.qtpl:114
		qw422016.N().D(cLen * lSymb)
//line views/templates/system/routeTable/table_row.qtpl:114
		qw422016.N().S(`px;
    `)
//line views/templates/system/routeTable/table_row.qtpl:115
		if columns[i].Type() == "timestamp" {
//line views/templates/system/routeTable/table_row.qtpl:115
			qw422016.N().S(`
    word-break: break-all;
    `)
//line views/templates/system/routeTable/table_row.qtpl:117
		}
//line views/templates/system/routeTable/table_row.qtpl:117
		qw422016.N().S(`
}
.usr-table-row{
 .table-col-`)
//line views/templates/system/routeTable/table_row.qtpl:120
		qw422016.N().D(i)
//line views/templates/system/routeTable/table_row.qtpl:120
		qw422016.N().S(`{
   text-align: `)
//line views/templates/system/routeTable/table_row.qtpl:121
		if columns[i].CharacterMaximumLength() > 0 {
//line views/templates/system/routeTable/table_row.qtpl:121
			qw422016.N().S(` left
                `)
//line views/templates/system/routeTable/table_row.qtpl:122
		} else {
//line views/templates/system/routeTable/table_row.qtpl:122
			qw422016.N().S(` right
              `)
//line views/templates/system/routeTable/table_row.qtpl:123
		}
//line views/templates/system/routeTable/table_row.qtpl:123
		qw422016.N().S(`;
  }
}
`)
//line views/templates/system/routeTable/table_row.qtpl:126
	}
//line views/templates/system/routeTable/table_row.qtpl:126
	qw422016.N().S(`
.table-custom{
    width: `)
//line views/templates/system/routeTable/table_row.qtpl:128
	qw422016.N().D(allWidth)
//line views/templates/system/routeTable/table_row.qtpl:128
	qw422016.N().S(`px;
}
</style>
`)
//line views/templates/system/routeTable/table_row.qtpl:131
}

//line views/templates/system/routeTable/table_row.qtpl:131
func WriteTableRow(qq422016 qtio422016.Writer, columns []dbEngine.Column, rows [][]interface{}) {
//line views/templates/system/routeTable/table_row.qtpl:131
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/templates/system/routeTable/table_row.qtpl:131
	StreamTableRow(qw422016, columns, rows)
//line views/templates/system/routeTable/table_row.qtpl:131
	qt422016.ReleaseWriter(qw422016)
//line views/templates/system/routeTable/table_row.qtpl:131
}

//line views/templates/system/routeTable/table_row.qtpl:131
func TableRow(columns []dbEngine.Column, rows [][]interface{}) string {
//line views/templates/system/routeTable/table_row.qtpl:131
	qb422016 := qt422016.AcquireByteBuffer()
//line views/templates/system/routeTable/table_row.qtpl:131
	WriteTableRow(qb422016, columns, rows)
//line views/templates/system/routeTable/table_row.qtpl:131
	qs422016 := string(qb422016.B)
//line views/templates/system/routeTable/table_row.qtpl:131
	qt422016.ReleaseByteBuffer(qb422016)
//line views/templates/system/routeTable/table_row.qtpl:131
	return qs422016
//line views/templates/system/routeTable/table_row.qtpl:131
}
