/*
 * Copyright (c) 2024. Author: Ruslan Bikchentaev. All rights reserved.
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file.
 * Перший приватний програміст.
 */

// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// All the text outside function templates is treated as comments,
// i.e. it is just ignored by quicktemplate compiler (`qtc`). It is for humans.

//line index.qtpl:3
package pages

//line index.qtpl:3
import (
	"github.com/ruslanBik4/httpgo/views/templates/layouts"
	"io"
)

// content of Index page

//line index.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.qtpl:10
type IndexPageBody struct {
	Name         []byte
	Pass         []byte
	Content      []byte
	ContentWrite func(w io.Writer)
	Buff         io.Writer
	Catalog      layouts.Menu
	TopMenu      layouts.Menu
	FooterMenu   layouts.Menu
	HeadHTML     *layouts.HeadHTMLPage
	OwnerMenu    *layouts.MenuOwnerBody
	Title        string
	Route        string
	Attr         string
	AfterAuthURL string
	ChangeTheme  string
	SearchPanel  *layouts.SearchPanel
}

//line index.qtpl:29
func (body *IndexPageBody) StreamIndexHTML(qw422016 *qt422016.Writer) {
//line index.qtpl:29
	qw422016.N().S(`
`)
//line index.qtpl:30
	body.HeadHTML.StreamHeadHTML(qw422016)
//line index.qtpl:30
	qw422016.N().S(`
<body `)
//line index.qtpl:31
	qw422016.E().S(body.Attr)
//line index.qtpl:31
	qw422016.N().S(`>
`)
//line index.qtpl:32
	layouts.StreamHeaderHTML(qw422016, body.TopMenu)
//line index.qtpl:32
	qw422016.N().S(`
<main class="content-wrap">
	<div id="container-fluid">
	        <div class="sidebar-section">
	            <div id="catalog_pane"  class="well sidebar-nav">
	                `)
//line index.qtpl:37
	body.Catalog.StreamRenderMenu(qw422016, "left-mnu-list", "left-mnu-item")
//line index.qtpl:37
	qw422016.N().S(`
	            </div>
	        </div>
	        <div class="content-section">
`)
//line index.qtpl:41
	if body.SearchPanel != nil {
//line index.qtpl:41
		qw422016.N().S(`			    <div class="row-fluid">
			          `)
//line index.qtpl:43
		body.SearchPanel.StreamRender(qw422016)
//line index.qtpl:43
		qw422016.N().S(`
			    </div>
`)
//line index.qtpl:45
	}
//line index.qtpl:45
	qw422016.N().S(`		        <div id="content" hx-get="`)
//line index.qtpl:46
	qw422016.E().S(body.Route)
//line index.qtpl:46
	qw422016.N().S(`" hx-trigger="load">
	            `)
//line index.qtpl:48
	if body.ContentWrite != nil {
		body.ContentWrite(body.Buff)
	} else {
		body.Buff.Write(body.Content)
	}

//line index.qtpl:53
	qw422016.N().S(`
		        </div>
	        </div>
	</div>
</main>
`)
//line index.qtpl:58
	layouts.StreamFooterHTML(qw422016, body.FooterMenu)
//line index.qtpl:58
	qw422016.N().S(`
</body>
`)
//line index.qtpl:60
}

//line index.qtpl:60
func (body *IndexPageBody) WriteIndexHTML(qq422016 qtio422016.Writer) {
//line index.qtpl:60
	qw422016 := qt422016.AcquireWriter(qq422016)
//line index.qtpl:60
	body.StreamIndexHTML(qw422016)
//line index.qtpl:60
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:60
}

//line index.qtpl:60
func (body *IndexPageBody) IndexHTML() string {
//line index.qtpl:60
	qb422016 := qt422016.AcquireByteBuffer()
//line index.qtpl:60
	body.WriteIndexHTML(qb422016)
//line index.qtpl:60
	qs422016 := string(qb422016.B)
//line index.qtpl:60
	qt422016.ReleaseByteBuffer(qb422016)
//line index.qtpl:60
	return qs422016
//line index.qtpl:60
}
