// Copyright 2018 Author: Ruslan Bikchentaev. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package telegrambot

const baseURL string = "https://api.telegram.org/bot"

const (
	cmdGetMe                     = "getMe"
	cmdSendMes                   = "sendMessage"
	cmdFormatOpt                 = "Formatting options"
	cmdFwdMess                   = "forwardMessage"
	cmdSendPhoto                 = "	sendPhoto"
	cmdSendAudio                 = "sendAudio"
	cmdSendDocument              = "	sendDocument"
	cmdSendVideo                 = "sendVideo"
	cmdSendAnimation             = "sendAnimation"
	cmdSendVoice                 = "sendVoice"
	cmdSendVideoNote             = "sendVideoNote"
	cmdSendMediaGroup            = "sendMediaGroup"
	cmdSendLocation              = "sendLocation"
	cmdEditMesLiveLoc            = "editMessageLiveLocation"
	cmdStopMesLiveLoc            = "stopMessageLiveLocation"
	cmdSendVenue                 = "sendVenue"
	cmdSendContact               = "sendContact"
	cmdSendPoll                  = "sendPoll"
	cmdSendChatAction            = "sendChatAction"
	cmdGetUsrPflPhoto            = "getUserProfilePhotos"
	cmdGetFile                   = "getFile"
	cmdKickChMbr                 = "kickChatMember"
	cmdUnbanChMbr                = "unbanChatMember"
	cmdResctrictChMbr            = "restrictChatMember"
	cmdPromoteChMbr              = "promoteChatMember"
	cmdSetChPerm                 = "setChatPermissions"
	cmdExportChLink              = "exportChatInviteLink"
	cmdSetChPhoto                = "setChatPhoto"
	cmdDelChPhoto                = "deleteChatPhoto"
	cmdSetChTitle                = "setChatTitle"
	cmdSetChDesc                 = "setChatDescription"
	cmdPinChMes                  = "pinChatMessage"
	cmdUnpinCHMes                = "unpinChatMessage"
	cmdLeaveCH                   = "leaveChat"
	cmdGetChat                   = "getChat"
	cmdSendgetChatAdministrators = "getChatAdministrators"
	cmdSendgetChatMembersCount   = "getChatMembersCount"
	cmdSendgetChatMember         = "getChatMember"
	cmdSetChatStickerSet         = "setChatStickerSet"
	cmddeleteChatStickerSet      = "deleteChatStickerSet"
	cmdanswerCallbackQuery       = "answerCallbackQuery"
	cmdInlineMThd                = "Inline mode methods"
)
